### ISSUE TITLE
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#102]
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Win32.TaskScheduler.V2Interop.TaskSchedulerClass.Connect(Object
 serverName, Object user, Object domain, Object password)
   at Microsoft.Win32.TaskScheduler.TaskService.Connect()
 
Memory is OK, Win7 with all last updates.
Computer restartes and so on does not help.
It runs from WCF service. .NET 4.0
It also repoducable on Win2008 R2 (btw, seems on old Win2008 it works fine).
I am not sure what additional information you could require.

Originally posted: 2011-06-22T11:46:24

**Comment by dahall** [comment]
I think you'll need to provide more code or context. This method has worked many times on multiple systems including the ones you indicate. There must be something in the way you are using threads, calling the method, or your runtime environment that is contributing to this condition. Please also provide the exact parameters that are passed in during the call.

Originally posted: 2011-06-23T00:33:34

**Comment by dahall** [comment]
User provided no further context. Closing due to lack of information.

Originally posted: 2011-10-14T15:51:05

**Comment by alfredormorales** [comment]
I have same issue with version 2.8.18, the strange thing it's was this only starts to happen before I ran various times my app, first I implement the code an make unit tests, the object register well the task, but rigth now I have this issue, I paste the code I'm using for make the task:

`try
            {
                string[] hourMinute = _hour.Split(':');
                short hour = Convert.ToInt16(hourMinute[0]);
                short minute = Convert.ToInt16(hourMinute[1]);
                string[] account = _user.Split('\\');

                using (
                TS.TaskService taskService = new TS.TaskService(System.Environment.MachineName,
                    _user, account[0], _password))
                {
                    TS.DailyTrigger trigger = new TS.DailyTrigger();
                    trigger.DaysInterval = 1;
                    trigger.ExecutionTimeLimit = new TimeSpan(0, 15, 0);
                    trigger.StartBoundary = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, hour, minute, 0);
                    TS.Task task = taskService.GetTask(_taskName);

                    //si la tarea ya existe, la borramos
                    if (task != null)
                    {
                        taskService.RootFolder.DeleteTask(_taskName);
                    }

                    var action = new TS.ExecAction(System.Windows.Forms.Application.ExecutablePath, "automatico");

                    taskService.AddTask(_taskName,
                        trigger, action, _user, _password, TS.TaskLogonType.Password);

                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }`

the "try", throw an excepction when the code run this line:
 using (TS.TaskService taskService = new TS.TaskService(System.Environment.MachineName,
 _user, account[0], _password))

The apps is a Winforms .NET 3.5, runing on windows 10.

Greetings

**Comment by alfredormorales** [comment]
> I have same issue with version 2.8.18, the strange thing it's was this only starts to happen before I ran various times my app, first I implement the code an make unit tests, the object register well the task, but rigth now I have this issue, I paste the code I'm using for make the task:
> 
> `try
> {
> string[] hourMinute = _hour.Split(':');
> short hour = Convert.ToInt16(hourMinute[0]);
> short minute = Convert.ToInt16(hourMinute[1]);
> string[] account = _user.Split('\');
> 
> ```
>             using (
>             TS.TaskService taskService = new TS.TaskService(System.Environment.MachineName,
>                 _user, account[0], _password))
>             {
>                 TS.DailyTrigger trigger = new TS.DailyTrigger();
>                 trigger.DaysInterval = 1;
>                 trigger.ExecutionTimeLimit = new TimeSpan(0, 15, 0);
>                 trigger.StartBoundary = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, hour, minute, 0);
>                 TS.Task task = taskService.GetTask(_taskName);
> 
>                 //si la tarea ya existe, la borramos
>                 if (task != null)
>                 {
>                     taskService.RootFolder.DeleteTask(_taskName);
>                 }
> 
>                 var action = new TS.ExecAction(System.Windows.Forms.Application.ExecutablePath, "automatico");
> 
>                 taskService.AddTask(_taskName,
>                     trigger, action, _user, _password, TS.TaskLogonType.Password);
> 
>             }
> 
>         }
>         catch (Exception ex)
>         {
>             throw ex;
>         }
>     }`
> ```
> 
> the "try", throw an excepction when the code run this line:
> using (TS.TaskService taskService = new TS.TaskService(System.Environment.MachineName,
> _user, account[0], _password))
> 
> The apps is a Winforms .NET 3.5, runing on windows 10.
> 
> Greetings

> @dahall

**Comment by dahall** [comment]
If you are just connecting to the local machine's Task Scheduler using the credentials of the current user, you do not need to construct a TaskService instance. You can use TaskService.Instance instead. This static property does not need to be disposed and is much gentler on system resources.

**Comment by alfredormorales** [comment]
Thank you, I think my problem is my PC had a (Hardware Or Bad OS Installation ) issue, Because I run my Winform App on other PC with windows 2012 server and add the task wtihouth memory exception on this PC.

My app needs to use other credential than the current user because the resident OS can have an account runing the os with write permisions on the folder I want to run the app.

thank you!
