### ISSUE TITLE
Please vote: Nullable Property Types

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#12]
A question to the community: I'm considering making a breaking change to the library and introducing nullable TimeSpan and nullable DateTime properties to more accurately reflect how some properties are handled by the native library. For example, the native library would set the EndBoundary value of a trigger to "null" if it was not set. In this library (created before nullable types), that value is artificially recast as DateTime.MaxValue. Please provide your thoughts and votes. It would align this library more to the native library.

**Comment by Smurf-IV** [comment]
Is it possible to use Both ? e.g.
i.e. via the existing set / getters have them return the Max (etc),
and introduce a new set / getter that allows direct access to the nullable type ?
