### ISSUE TITLE
my scheduler task not working properly after then

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#126]
"the selected task {0} no longer exists. to see the current task click refresh" task scheduler throwing exception while  boot up and refreshing.

Originally posted: 2013-04-25T07:23:53

**Comment by dahall** [comment]
This error is not coming from this library. Are you seeing this error from the Windows Task Scheduler application? If so, then please contact Microsoft for support.

Originally posted: 2013-04-29T10:19:07

**Comment by dahall** [comment]
There is a potential race condition when multiple instances of the COM object access the same task. I handle this exception in the library, but the native application does not. This is the error you are seeing. The only way to avoid it is to not access the same task through the library that is being viewed in the native app.

Originally posted: 2013-04-29T15:49:44

**Comment by ronak-k-p** [comment]
https://github.com/dahall/TaskScheduler/issues/126#issuecomment-381342461 
Native App ! does that mean "Task Scheduler" or Application where we are using this library

So if i keep native app closed and any action performed by library(like create task folder/ task  or delete task folder / task)
will not have this issue !

**Comment by dahall** [comment]
Both. Any time the COM object for a task is held active (and the Window "Task Scheduler" app does, any other instances of the COM object cannot operate. This can also happen if your app has the object active and the Windows app tries to access it. Effectively, using developer parlance, the `IRegisteredTask` object is non-reentrant at the system level.
