### ISSUE TITLE
Tasks not visible to library after upgrade to Windows 10 or Windows Server 2016

### ISSUE THREAD

**Issue by hitessh18** [dahall/TaskScheduler#13]
There are many tasks created on a Server machine using this library. Now the Server has been upgraded from Windows Server 2012 R2 to Windows Server 2016. All the tasks in the old server was exported and now imported in the new Server. 

All the tasks are running correctly. But somehow when my application tries to find the tasks via FindTask(), it returns null. Below is the code I am using to find the task.

`TaskService st = new TaskService();`
`Task oTask = st.FindTask("{A689610E-EC51-4288-A8EB-3847B4AB152D}");`

Below is the snap of the Task scheduler with the same task working normal.
![image](https://user-images.githubusercontent.com/16350538/31648394-101d24dc-b32b-11e7-89d5-6dad9331b5e2.png)

Steps to reproduce the issue:-
1. Create a task with a unique name (say T1) using this API. 
2. Export the task T1 from the Task scheduler of windows machine manually.
3. Delete the task T1 from the Task scheduler of windows machine manually.
4. Import the task T1 from the Task scheduler of windows machine manually.
5. Try to find the task T1 via `st.FindTask("T1");` it returns null.

I am facing this issue on the Server and not able to read the tasks at all since I can't find them.
Please suggest a way to read all these tasks. 

Thanks,
Jeet Doshi

**Comment by dahall** [comment]
Will you provide the XML that you export? Windows 10 and Server 2016 added a new default security access permission to the base. I have seen this affect importing. Have you tried using the API to re-create the task? If so, do you observe the same problem?

**Comment by hitessh18** [comment]
Check this [XML](https://drive.google.com/open?id=0B5gc8M5EOKshWFJnX3YyenlTRk0) of the export.
Also after I import the above XML in the task scheduler, the created tasks' export can be found [here](https://drive.google.com/open?id=0B5gc8M5EOKshZ0RkSF9FUF90RFU). 

I did not get chance to re create the task using API on the client's machine as they already did the migration thing. But I did try the same steps using API in my machine. It works fine when the entire scenario is done using the API. 

Check the below sample code that I ran. 
` static void Main(string[] args)
        {
            Console.WriteLine("Begin creating task to open notepad at 9:30 everyday.");

            // Create a new task definition for the local machine and assign properties
            TaskDefinition td = TaskService.Instance.NewTask();
            td.RegistrationInfo.Description = "Does something";

            // Add a trigger that, starting tomorrow, will fire every other week on Monday
            // and Saturday and repeat every 10 minutes for the following 11 hours
            WeeklyTrigger wt = new WeeklyTrigger();
            wt.StartBoundary = DateTime.Today.AddDays(1);
            wt.DaysOfWeek = DaysOfTheWeek.Monday | DaysOfTheWeek.Saturday;
            wt.WeeksInterval = 2;
            wt.Repetition.Duration = TimeSpan.FromHours(11);
            wt.Repetition.Interval = TimeSpan.FromMinutes(10);
            td.Triggers.Add(wt);

            // Create an action that will launch Notepad whenever the trigger fires
            td.Actions.Add("notepad.exe", "c:\\test.log");

            // Register the task in the root folder of the local machine
            TaskService.Instance.RootFolder.RegisterTaskDefinition("Test", td);

            Task otask = TaskService.Instance.FindTask("Test");
            if (otask != null)
                Console.WriteLine("Task created succesfully");

            Console.WriteLine("Begin Export the task to C drive.");
            otask.Export("c:\\Test_export");
            Console.WriteLine("Export done successfuly..");

            Console.WriteLine("Begin Delete the task.");
            TaskService.Instance.RootFolder.DeleteTask("Test");
            if (TaskService.Instance.FindTask("Test") == null)
                Console.WriteLine("Task deleted succesfully");

            Console.WriteLine("Begin Import the task directly from the file.");
            TaskService.Instance.RootFolder.ImportTask("Test", "c:\\Test_export");
            if (TaskService.Instance.FindTask("Test") != null)
                Console.WriteLine("Task imported succesfully");

            Console.ReadKey();
        }`

**Comment by dahall** [comment]
I have verified that this is a problem with the Windows Task Scheduler MMS and the import function. This happens consistently on Windows 10 and Server 2016. This is a problem related to Microsoft and their changes to permissions in the newer OS.

I'm in the process of adding new methods to the library that can import and export from one system to another. I'll post here with the link to the new release once it is operational.
