### ISSUE TITLE
How to call function/method from TaskScheduler

### ISSUE THREAD

**Issue by FrancisND** [dahall/TaskScheduler#14]
Hi, I've been looking to contact you since long time.

I tested your product and working perfect but I have a concern.

I'm using VB.Net and want to call a VB method from "Microsoft.Win32.TaskScheduler".
I know that many examples describe about how to open file/application and so on which is external to vb.net ... but I want to call something internal (vb function/method)

How can i do that please? is it possible?

**Please see below.**

` "td.Actions.Add(New ExecAction("MyMethod()", "c:\test.log"))"

    Sub MyMethod()

        MsgBox("Working !!!")

    End Sub`

**Comment by dahall** [comment]
There is no mechanism to do exactly as you've written, that is calling a VB method directly from a task. However, you can have a task call a ComHandlerAction this is hosted by a VB COM object. For an example in C# (sorry, no template or code for VB), see https://github.com/dahall/ITaskHandlerTemplate.
