### ISSUE TITLE
Feature Request: documentation in PDF file

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#195]
Hello. Today I spent some time trying to make Visual Studio Documentation working without any success. I needed detailed description of the interfaces, so I had to reverseengineer the source code of the Task Scheduler Managed Wrapper. It would be great if the documentation in PDF or any other readable mode becomes available so other users don't have to reverseengineer the source code :)

Originally posted: 2016-08-22T09:23:36

**Comment by dahall** [comment]
The help is available as an MS Help 2.0 file from the downloads page. There is an installation batch file in the .ZIP file.

Originally posted: 2016-08-22T17:58:02

**Comment by InteXX** [comment]
@dahall 

> The help is available as an MS Help 2.0 file from the downloads page.

Where can we find the downloads page?

**Comment by dahall** [comment]
https://github.com/dahall/TaskScheduler/releases

**Comment by dahall** [comment]
https://github.com/dahall/TaskScheduler/releases

**Comment by InteXX** [comment]
@dahall Got it, thank you.
