### ISSUE TITLE
.NET Core Port

### ISSUE THREAD

**Issue by droyad** [dahall/TaskScheduler#2]
We use your library, so thank you for making it available and maintaining it. We are looking at moving to .NET Core, and I'm wondering what your plans are for making a .NET Core version available as well.

I've [attempted a port](https://github.com/droyad/TaskScheduler/pull/1) of the `TaskService` projects, and the only bit I found that wasn't supported is the `WindowsImpersonationContext` and the `EventLog` stuff.

**Comment by dahall** [comment]
I'm mostly there with the project updates I just posted. I now just need to figure out how to build both the .NET Standard assembly and the multiple .NET Framework assemblies at the same time. All the files and project are updated and I just have the .NET Standard build line commented out.

**Comment by droyad** [comment]
@dahall Just add `netstandard2.0` into existing `TargetFrameworks` element in https://github.com/dahall/TaskScheduler/blob/master/TaskService/TaskService.csproj#L4

**Comment by dahall** [comment]
Done, and it works. You have to add it after the .NET Framework builds or VS has a problem. I just checked in those changes. I will do some testing and tweaks to make sure the disabled features fail gracefully and then release a NuGet package with the support.

**Comment by droyad** [comment]
oh, Awesome! Thanks for that. Interesting about the order, I did have an issue where the restore didn't work.

**Comment by dahall** [comment]
Just a status update: I am waiting to push the code until I can adequately test it in a UWP or console app. I can't do that until MS releases VS 2017 15.4. So, as soon as that update comes out, I will test and then release a NuGet with netstandard2.0 included.

**Comment by dahall** [comment]
I figured out a way to test ahead of VS15.4 and have run into a big problem. .NET Standard 2.0 does not support COM IEnumerable. This interfaces is used extensively by Microsoft in the base library. I'm looking for work arounds, but, so far, have come up empty. This may need to be put on hold until MS added COM support to .NET Standard. Thoughts?

**Comment by droyad** [comment]
Which part of the code has those IEnumerables?

**Comment by dahall** [comment]
The native COM objects IActionCollection, ITriggerCollection, IRegisteredTaskCollection and IRunningTaskCollection are all native COM interfaces that support a special COM version of IEnumerable. The .NET interop code that handles working with COM doesn't implement that special IEnumerable so it can't convert it to the .NET version.

**Comment by kswierszczyk** [comment]
Same issue w/ the IEnums. I'll be looking at possible solutions also as I'd like to migrate a project to .NET core. Has there been any word from Microsoft as to whether they'll be adding COM support to .NET Standard?

**Comment by dahall** [comment]
Microsoft has not even hinted as of today on what will be a part of the next .NET Standard release.

**Comment by droyad** [comment]
It looks like they don't intend to support `GetEnumerator()`, https://github.com/dotnet/corefx/issues/19731

However, I think I have found a work around. It works for the `TestTaskServiceConsole` app. See PR #35

**Comment by dahall** [comment]
Wow. Thanks for this workaround. How comfortable are you that the changes in your PR do not change any of the API (breaking change)? I'd be glad to just pull them straightway, but don't want to break anyone's existing code.

**Comment by dahall** [comment]
Added to release 2.7.2! Thanks for your help.

**Comment by droyad** [comment]
@dahall No worries. I didn't test all the methods, just the enumerating the tasks. I did just realise that I incorrectly `0` indexed the other arrays, but it doesn't look like that made it into `master`.

Thanks, I'll try it out!
