### ISSUE TITLE
Repetitive (One Time Trigger) Schedule does not run on the last/final "Next Run Time"

### ISSUE THREAD

**Issue by Jaryllan** [dahall/TaskScheduler#26]
I have an issue where it only occurred on One Time trigger with repetitive configured. It doesn't run on the last/final "Next Run Time" and it only happens when the task is created from code.

For example: 
When i set it to start the schedule on **10:00:00 AM** and to **repeat the task every 1 minute for a duration of 2 minutes**. The task executed at 10:00:00 AM & 10:01:00 AM, but at 10:02:00 AM did not get executed even though the "Next Run Time" did specify to run at 10:02:00 AM in task scheduler window.

Did not find anything on history tab and the event log. There is no error and it did not stamp any information for 10:02:00 AM.

I have tried to manually create the task through the task scheduler window and it doesn't have this problem.

Version tried on "2.5.21" & "2.6.3".
Tested on Windows Server 2016 & Windows Server 2012 R2.

`using (var taskService = new TaskService())
{
    var taskSchedulerFolder = @"Tasks Folder\CustomSchedulerProcessor";

    var taskDefinition = taskService.NewTask();
    var registrationInfo = taskDefinition.RegistrationInfo;
    registrationInfo.Date = DateTime.Now;

    var settings = taskDefinition.Settings;
    settings.StartWhenAvailable = true;
    settings.AllowDemandStart = false;
    settings.MultipleInstances = TaskInstancesPolicy.IgnoreNew;
    settings.DisallowStartIfOnBatteries = false;
    settings.StopIfGoingOnBatteries = false;

    var trigger = new TimeTrigger();
    trigger.StartBoundary = DateTime.Now.AddSeconds(5);
    trigger.Repetition.Interval = new TimeSpan(0, 1, 0);
    trigger.Repetition.Duration = new TimeSpan(0, 2, 0);
    trigger.Repetition.StopAtDurationEnd = false;

    using (trigger)
    {
        taskDefinition.Triggers.Add(trigger);

        using (var execAction = new ExecAction(@"E:\OneTimeConsole.exe"))
        {
            taskDefinition.Actions.Add(execAction);

            var logonUser = string.Empty;

            using (var currentWindowsIdentity = WindowsIdentity.GetCurrent())
            {
                logonUser = (new WindowsPrincipal(currentWindowsIdentity)).Identity.Name;
            }

            taskDefinition.RegistrationInfo.Author = logonUser;

            taskService.GetFolder(taskSchedulerFolder).RegisterTaskDefinition(Guid.NewGuid().ToString().Replace("-", string.Empty), taskDefinition, TaskCreation.Create, logonUser, logonType: TaskLogonType.InteractiveToken);
        }
    }
}`

**Comment by dahall** [comment]
It appears that the code you have is the cause of your problem. You have specified a duration of 1 min.
```
// This line is from your code and sets the duration to 1 minute.
trigger.Repetition.Duration = new TimeSpan(0, 1, 0);
// Change it to this line to get the 2 minute duration
trigger.Repetition.Duration = TimeSpan.FromMinutes(2);
```

**Comment by Jaryllan** [comment]
Sorry, it was my mistake. The code did not describe the issue correctly. I have amend it to 2 minutes.

trigger.Repetition.Duration = new TimeSpan(0, 2, 0);

**Comment by dahall** [comment]
So with the corrected code, do you still have the issue reported?

**Comment by Jaryllan** [comment]
Anyway, i have perform some testing to re-simulate the above case and noticed that the task created from the code ticks the "Synchronize across time zone", whereas in my manually created task in task scheduler windows, i did not tick the "Synchronize across time zone". So once I tick that, it behaves the same as the task being created from the code. 

So it isn't an issue anymore and there's no bug in the code, since it behave the same as what it is being created manually in task scheduler window.

Kind of weird that once "Synchronize across time zone" is ticked, the task will not run the final/last "Next Run Time".

**Comment by dahall** [comment]
That is peculiar, but it appears to be a problem with native Microsoft library then.
