### ISSUE TITLE
In Task editor, selecting a COM object from the list injects the name into the text field, not the GUID

### ISSUE THREAD

**Issue by Gwindalmir** [dahall/TaskScheduler#28]
The selected COM object has its name inserted into the text field, instead of the GUID, this causes a validation error in ComHandlerActionUI.comCLSIDText_Validating

1) Edit Task
2) Select Add New Action
3) Select Custom handler
4) Select the Browse button, and "Lookup CLSID"
5) Select a COM object
6) Notice the name is returned, instead of the GUID, this causes a red validation error to appear.
![image](https://user-images.githubusercontent.com/1127170/32249866-ab8ed74a-be47-11e7-9d44-83f1f54a60c2.png)

The error is "Invalid GUID for CLSID"

This is the same class I selected in issue #27 .

In a slightly related issue, if you select "Manually Enter CLSID", the OK button is not enabled unless you already tried to select a COM server in the browse list.

**Comment by dahall** [comment]
These items (text from lookup dialog and manual entry validation) have been fixed and committed and will be in the next release (likely 2.6.4).
