### ISSUE TITLE
TaskDefinition.Principal.UserId in Windows 2016

### ISSUE THREAD

**Issue by bhalbright** [dahall/TaskScheduler#29]
TaskScheduler 2.6.3

Hello, I setup a scheduled task to be run by a user in Windows 2016, when I look at that task via the TaskScheduler library, the TaskDefinition.Principal.UserId for this task is an empty string. If I look at the raw XML for the task:

	<Principals>
		<Principal id="Author">      
			<UserId>S-1-5-21-#########-##########-##########-####</UserId>      
			<LogonType>Password</LogonType>      
			<RunLevel>LeastPrivilege</RunLevel>    
		</Principal>  
	</Principals>  

I can see the SID instead of the user id which is defined as a possibility (https://msdn.microsoft.com/en-us/library/cc248346.aspx). However, I don't see that SID in any of the fields exposed in the TaskPrincipal object (or anywhere else in the Task object).

Should I expect it to be, or am I possibly doing something wrong? I mentioned Windows 2016, but I don't know if this is really specific to Windows 2016, it just is the only OS I've run into this on. Thanks!

**Comment by dahall** [comment]
The XML (for portability) will save the current user's SID as the UserId. The library (both this wrapper and the native library) stores that value as an empty string when it is the current user.

**Comment by bhalbright** [comment]
Thanks @dahall for such a quick reply! If you don't mind me asking, what is meant by "current user" in your explanation? Only asking because in my scenario, the user that created the task is not the same user that executes the task. I can see the executing user's SID in the xml, but that doesn't get exposed via your library. Of course there's no reason for your library to do anything if the native library doesn't. But it sounds like from my scenario if I really want to know the user, I'll need to grab the xml and parse out the principal information.
