### ISSUE TITLE
Suggestion for Task.LastTaskResult

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#291]
I was looking for what values can be returned through the LastTaskResult property, but I found two strange sets of error code for v1 and v2 correspondingly: [IScheduledWorkItem::GetExitCode](http://msdn.microsoft.com/en-us/library/aa381245(v=VS.85).aspx) and [IRegisteredTask::LastTaskResult](http://msdn.microsoft.com/en-us/library/aa380762(VS.85).aspx), which actually didn't help me at all.

Later I found [Task Scheduler Error and Success Constants](http://msdn.microsoft.com/en-us/library/aa383604(VS.85).aspx). Unfortunately it looks like it is applicable only for Task Scheduler v2.0.

Will you include it in next TaskScheduler library releases? I've used it at my side, but probably it could be useful for others.

And don't you know similar codes for Task Scheduler 1.0?

Best regards,

Sergey

Originally posted: 2010-10-18T09:17:50

**Comment by dahall** [comment]
Those constants are typically used as HResults when the native COM library methods fail or succeed. Since those codes are part of the standard error codes supported by .NET, the COMExcpetion will pull that code and try and find the localized text for the error.



Where are you needing these values? If they are useful in a specific use case, I would love to design for it and incorporate it. The LastTaskResult property is the exit code from the last running of an ExecAction.



Originally posted: 2010-10-18T15:11:55

**Comment by dahall** [comment]
Sorry, you are right. I got this code: SCHED\_S\_TASK\_TERMINATED (0x00041306): The last run of the task was terminated by the user.



as a LastTaskResult and thought other values could be useful. So yes, these values are not very helpful.



But how Task Scheduler in Windows does process return codes? It diplays both: message and code. Are they hardcoded in Windows? :)



Originally posted: 2010-10-19T00:27:34

**Comment by dahall** [comment]
Those codes are hardcoded and I have seen them appear usually as the error code within a COMException. Your example of those codes being returned by LastTaskResult is new to me. The textual message associated with each code is also hardcoded and is part of the localized error resources within Windows.



Originally posted: 2010-10-19T11:38:03

**Comment by dahall** [comment]
From all the messages discussing Task.LastTaskResult, this thread seems to be the most detailed.  But it's not very clear.  
  
This library returns an integer (without much meaning) as the value for Task.LastTaskResult. Yet Windows task scheduler is able to display a meaningful message such as the ones shown in this [image](http://screencast.com/t/OlfevgbL4hgT). Also, the Microsoft documentation for RegisteredTask.LastTaskResult property indicates it as a STRING property.  
  
Can you clarify why the wrapper library can't provide the same useful information that the Windows Task Scheduler is providing for the Last Task Result?  


Originally posted: 2015-12-19T15:33:09

**Comment by dahall** [comment]
The Scripting library referenced translates the HRESULT value to a string. The COM library (which is what is used for this wrapper) returns an HRESULT as stated in earlier posts ([https://msdn.microsoft.com/en-us/library/windows/desktop/aa380762(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380762(v=vs.85).aspx)). You can call [Marshal.GetExceptionForHR](https://msdn.microsoft.com/library/t8t3ykxc(v=vs.100).aspx) and then use the Message property to get the translated system description for that HRESULT.  

string errorMessage = Marshal.GetExceptionForHR(task.LastTaskResult).Message;


Originally posted: 2015-12-21T11:10:04

**Comment by dahall** [comment]
Thanks.  


Originally posted: 2015-12-21T17:09:40

**Comment by cn-qlg** [comment]
`Marshal.GetExceptionForHR(task.LastTaskResult).Message`, sometimes does't work.
For example, task.LastTaskResult = 267014, according to the link above, it should be 0x41306, `SCHED_S_TASK_TERMINATED The last run of the task was terminated by the user.`
But acctually, it raise an Exception, because `Marshal.GetExceptionForHR` cannot find the Exception from the errcode.

**Comment by dahall** [comment]
You can always determine an HRESULT error by seeing if the highest order bit is set. Here is not so that is a clue. 'SCHED_S_TASK_TERMINATED' is a Win32 error and therefore would need to be cast to an HRESULT using the C++ macro WIN32_TO_HRESULT. The equivalent in C# is `(err & 0x0000FFFF) | 0x80070000'. For this error, how does `Marshal.GetExceptionForHR(0x80071306).Message` perform?

**Comment by cn-qlg** [comment]
Cannot run directly, because 0x80071306 is out of integer. And i do this, `Console.WriteLine(Marshal.GetExceptionForHR(unchecked((int)2147947270)))` then got msg "System.Runtime.InteropServices.COMException (0x80071306): Exception comes from HRESULT:0x80071306".

**Comment by cn-qlg** [comment]
Here are some code I used to got the message from the Task.LastTaskResult, and works for me.
```
 enum ScheduleExceptionCode
    {
        SCHED_S_Task_Finished = 0, // 0x0 The operation completed successfully. 
        SCHED_S_TASK_READY = 267008, // 0x00041300 The task is ready to run at its next scheduled time.
        SCHED_S_TASK_RUNNING = 267009, // 0x00041301 The task is currently running.
        SCHED_S_TASK_DISABLED = 267010, // 0x00041302 The task will not run at the scheduled times because it has been disabled.
        SCHED_S_TASK_HAS_NOT_RUN = 267011, // 0x00041303 The task has not yet run.
        SCHED_S_TASK_NO_MORE_RUNS = 267012, // 0x00041304 There are no more runs scheduled for this task.
        SCHED_S_TASK_NOT_SCHEDULED = 267013, // 0x00041305 One or more of the properties that are needed to run this task on a schedule have not been set.
        SCHED_S_TASK_TERMINATED = 267014, // 0x00041306 The last run of the task was terminated by the user.
        SCHED_S_TASK_NO_VALID_TRIGGERS = 267015, // 0x00041307 Either the task has no triggers or the existing triggers are disabled or not set.
        SCHED_S_EVENT_TRIGGER = 267016, // 0x00041308 Event triggers do not have set run times.
        SCHED_E_TRIGGER_NOT_FOUND = unchecked((int)2147750665), // 0x80041309 A task's trigger is not found.
        SCHED_E_TASK_NOT_READY = unchecked((int)2147750666), // 0x8004130A One or more of the properties required to run this task have not been set.
        SCHED_E_TASK_NOT_RUNNING = unchecked((int)2147750667), // 0x8004130B There is no running instance of the task.
        SCHED_E_SERVICE_NOT_INSTALLED = unchecked((int)2147750668), // 0x8004130C The Task Scheduler service is not installed on this computer.
        SCHED_E_CANNOT_OPEN_TASK = unchecked((int)2147750669), // 0x8004130D The task object could not be opened.
        SCHED_E_INVALID_TASK = unchecked((int)2147750670), // 0x8004130E The object is either an invalid task object or is not a task object.
        ……
    }

    var scheduleCode = (ScheduleExceptionCode)Enum.ToObject(typeof(ScheduleExceptionCode), task.LastTaskResult);

    switch (scheduleCode)
     {
         case ScheduleExceptionCode.SCHED_S_Task_Finished:
             return "The operation completed successfully. ";
         case ScheduleExceptionCode.SCHED_S_TASK_READY:
             return "The task is ready to run at its next scheduled time.";
         case ScheduleExceptionCode.SCHED_S_TASK_RUNNING:
              return "The task is currently running.";
          ……
    }
```

**Comment by dahall** [comment]
Here's the code I used in the GUI control `TaskListView` that seems to work:
```cs
string LastResultString()
{
   if (task.State == TaskState.Running)
      return string.Format(EditorProperties.Resources.LastResultRunning, task.LastTaskResult);
   if (task.LastTaskResult == 0)
      return EditorProperties.Resources.LastResultSuccessful;
   var exc = new Win32Exception(task.LastTaskResult);
   if (string.IsNullOrEmpty(exc.Message))
      return string.Format("(0x{0:X})", task.LastTaskResult);
   return exc.Message.IndexOf(task.LastTaskResult.ToString("X"), StringComparison.InvariantCultureIgnoreCase) == -1 ? string.Format("{1} (0x{0:X})", task.LastTaskResult, exc.Message) : exc.Message;
}
```

**Comment by cn-qlg** [comment]
Thanks, seems that better than mine.
