### ISSUE TITLE
How do I view the downloaded help file?

### ISSUE THREAD

**Issue by Wardrop** [dahall/TaskScheduler#3]
I'm sorry if this is obvious to most Windows developers, but I have no idea how to view the help file after running the bat file?

**Comment by dahall** [comment]
That batch file installs the Task Scheduler help files into your local Microsoft Help Viewer instance. For information on how to use the local instance of help, see https://docs.microsoft.com/en-us/visualstudio/ide/microsoft-help-viewer. Now that I'm hosting on GitHub, I'm looking at ways to publish the help directly here.

**Comment by dahall** [comment]
Your post inspired me to figure it out. You can now find the help at https://dahall.github.io/TaskScheduler.

**Comment by Wardrop** [comment]
Excellent, much appreciated!
