### ISSUE TITLE
Create process under user interactive terminal with higher permissions

### ISSUE THREAD

**Issue by GieltjE** [dahall/TaskScheduler#31]
If the answer is "not possible" I would completely understand, I'm asking just to be sure.

We have a lot of different end user systems which require regulare updates. Some of those updates require administrative permissions and some of these systems have a password requirement for those permissions.

Creating a task that runs under SYSTEM with the proper access rules added can run these updates.
But some of these updates *might* hang and require user interaction.
Is there a way to run them as system/administrator/administrators but with the UI part visible for the current user?

Using runas gives some flags that hint that it could, but so far my attempts have been fruitless.

**Comment by dahall** [comment]
In my experience, the only way to do this is to run as the interactive user and then have the patch installers run in the background until there is an error.
