### ISSUE TITLE
How to set the Task Scheduler to repeat indefinitely?

### ISSUE THREAD

**Issue by TechieInventor** [dahall/TaskScheduler#33]
After referring to samples "https://github.com/dahall/TaskScheduler/wiki" and the api documentation for RepetitionPattern class "https://dahall.github.io/TaskScheduler/html/T_Microsoft_Win32_TaskScheduler_RepetitionPattern.htm". I'm not able to find how to set the repetitive duration to run "indefinitely". Is it possible to create a task scheduler with the repetition duration is indefinitely?

I have also tried assigning TimeSpan.MaxValue to trigger.Repetition.Duration, but it seems not possible with the application end up throwing exception.

**Comment by dahall** [comment]
Set Duration to TimeSpan.Zero.
