### ISSUE TITLE
Enforce 260 character limit for arguments <= Win 8

### ISSUE THREAD

**Issue by GieltjE** [dahall/TaskScheduler#36]
On windows 8 and below (including the server 2012 counterpart) tasks fail indefinitely (remain running till the machine is rebooted, but never actually execute) when the argument passed to them is longer than 260 characters with errorcode 2147942487.

Windows 10 doesn't seem to suffer from this problem (thankfully), could we add a filter/exception for this so other people don't bump their toes on this problem?

**Comment by dahall** [comment]
Are you referring to the Arguments property of the ExecAction class?

**Comment by GieltjE** [comment]
public RunningTask Run(params string[] parameters);

**Comment by dahall** [comment]
Included in 2.7.2

**Comment by GieltjE** [comment]
My sincere apologies, you wrote a proper patch and my wording wasn't accurate enough.

259 is the maximum usable count, 260 causes the mentioned problems.

"Added error handling on Task.Run and RunEx to ensure that prior to Win10" <-- don't hang?

**Comment by dahall** [comment]
That darn "inclusive" vs. "exclusive" phrase that too often gets left out of design docs! No problem, I'll correct. Thanks for finding the limitation.

**Comment by GieltjE** [comment]
Thank you for being a good maintainer 👍

**Comment by dahall** [comment]
Since you're online, let me ask another question:
```c#
if (TaskService.HighestSupportedVersion < TaskServiceVersion.V1_5 && parameters.Any(p => (p?.Length ?? 0) >= 260))
   throw new ArgumentOutOfRangeException(nameof(parameters), "On systems prior to Windows 10, no individual parameter may be more than 260 characters.");
```
This is the exception handler I've put in. I'm throwing an exception to let the developer know of the limitation rather than truncating the string. Is that your expectation? I voted against truncating the string because it would be an unknown side-effect without explanation. Another alternative is to just document it. What are your thoughts?

**Comment by GieltjE** [comment]
Personally I do prefer exceptions over silent truncation/modification, this makes it clear that there is something out of bounds.

We also run all our programs with "Check for arithmetic overflow/underflow" and treat warnings as errors when debugging.

Using this mindset it takes a bit longer to implement things but creates better code and awareness (in my opinion).
