### ISSUE TITLE
The request is not supported 0x80070032

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#365]
Hi All:

I use this wrapper(in my winform app) well to run a remote host'scheduler from one win xp 32bit computer,

but a error happen(

| **The request is not supported 0x80070032** |

)

when i run my winform app into a win 7 64 bit computer.

any suggestion???

thanks a lot.

﻿

Originally posted: 2011-10-19T03:27:53

**Comment by dahall** [comment]
Will you provide the code that throws this exception? That error condition can occur in a number of circumstances.



Originally posted: 2011-10-19T08:17:13

**Comment by dahall** [comment]
Hi dahall:



thank for your reply.



here is my code:


public class EmailSenderWindowTask
        {//remote Server        private string WindowSchedulerServer = System.Configuration.ConfigurationManager.AppSettings["EmailSenderWindowSchedulerServer"];        private string WindowSchedulerName = System.Configuration.ConfigurationManager.AppSettings["EmailSenderWindowSchedulerName"];       private DomainUser dUser = new DomainUser();        
        	public void Run()
        	{            		
        	       dUser.LoadByDefault();
                        using (TaskService ts = new TaskService(WindowSchedulerServer, dUser.Name, dUser.Domain, dUser.Password, false))             		
                         {                                 			
                            ts.GetTask(WindowSchedulerName).Run();
                        }        	
    	}
    
                public void Run(int pid)         	
                {             		
                        using (TaskService ts = new TaskService(WindowSchedulerServer, dUser.Name, dUser.Domain, dUser.Password, false))             		
                        {                 			
                            ts.GetTask(WindowSchedulerName).Run(pid.ToString());                            		
                        }        	
                 }
         }
    
    
    
    
    
            private void button2_Click(object sender, EventArgs e)
            {
                try
                {
                    new EmailSenderWindowTask().Run();
                    MessageBox.Show("Test Ok");
                }
                catch (Exception ex)
                {
                    MessageBox.Show(string.Format("Exception:{0}", ex.Message));
                    throw;
                }
    
            }
            
    
    
    BTW,My window form app must set Platform target to only x86 for runn in the win 7 64bit.


Originally posted: 2011-10-19T09:36:12

**Comment by dahall** [comment]
Does the TaskService constructor, the GetTask method, or the Run method throw the exception?



Originally posted: 2011-10-19T16:50:50

**Comment by dahall** [comment]
Hi dahall:



ok i will try to get which throw the exception.



I give you another exception first.



System.Runtime.InteropServices.COMException (0x80070032): The requester is not supported ( HRESULT: 0x80070032)



Originally posted: 2011-10-20T03:49:10

**Comment by dahall** [comment]
Without knowing which call into the library is throwing the exception, it is almost impossible to determine the cause.



Originally posted: 2011-10-20T08:56:55

**Comment by dahall** [comment]
hi dahall:



After I test, the  TaskService constructor throw this Exception.











Originally posted: 2011-10-20T21:21:43

**Comment by dahall** [comment]
Sometimes this happens when the Task Scheduler service or the Windows Event Log service has not been started. This can also happen on systems that have been imaged (sys prep'd) incorrectly.



Originally posted: 2011-10-21T07:26:59

**Comment by dahall** [comment]
I'm experiencing exactly the same problem. Trying to create a remote task, the code runs on Win7 32Bit, the destination PC is 2003 Server. Manually I can create a task to run on another computer, all good - which likely means that my system is suitably configured. But TaskService constructor throws with 0x80070032.



Originally posted: 2012-09-20T03:52:31

**Comment by dahall** [comment]
I am having the same problem connecting to a 2003 Server  
The request is not supported. (Exception from HRESULT: 0x80070032)  
  
my code is fairly simple, I'm just trying to connect at the moment   


    string strUsername = ConfigurationManager.AppSettings[&quot;Username&quot;];
                string strPassword = ConfigurationManager.AppSettings[&quot;Password&quot;];
                string strServer = ConfigurationManager.AppSettings[&quot;Server&quot;];
                string strDomain = ConfigurationManager.AppSettings[&quot;Domain&quot;];
    
                using (TaskService ts = new TaskService(strServer, strUsername, strDomain, strPassword))
                {
                    foreach (Task task in ts.RootFolder.Tasks)
                    {
                        string strName = task.Name;
                    }
                }

has anyone found the source of this problem or a solution?  
  
thanks  


Originally posted: 2013-05-07T08:52:44

**Comment by dahall** [comment]
FWIW, after trial and error I was able to connect to a 2003 server by specifying true for the forceV1 parameter and dropping the preceding backslashes from the targetServer parameter (ex. "SERVERNAME" instead of "\\SERVERNAME").  


Originally posted: 2013-10-31T14:22:24

**Comment by dahall** [comment]
I found a solution for this problem. A Firewall setting needs to be set.  
  
Go to: Windows Firewall => Allowed Programs, scroll down to "Remote Scheduled Task Management" and check that option. In my case just checking the "domain" option was enough.  


Originally posted: 2014-05-02T13:52:49

**Comment by GregTrevellick** [comment]
Specifying true for the forceV1 parameter fixed it for me
