### ISSUE TITLE
Determine highest possible TaskCompatibility

### ISSUE THREAD

**Issue by GieltjE** [dahall/TaskScheduler#37]
What is the best way to determine the maximum TaskCompatibility supported by the current system?

**Comment by dahall** [comment]
TaskCompatibility corresponds to the version of the library reported by the HighestSupportedVersion property of a TaskService instance.

HighestSupportedVersion | TaskCompatibility
---|---
1.1 | V1
1.2 | V2
1.3 | V2_1
1.4 | V2_2
1.5 | V2_3
1.6 | V2_3
