### ISSUE TITLE
Exception (23,8):UserId

### ISSUE THREAD

**Issue by ajcsoftware** [dahall/TaskScheduler#39]
I have had a few users get the following error but I have no idea what is causing it.  Seems like it might be a user logon issue but I'm told they were using the correct Windows logon details.  Does anyone know what the error means?

Exception: (23,8):UserId:
   at
Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(S
tring Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String
path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   at Microsoft.Win32.TaskScheduler.TaskEditDialog.okBtn_Click(Object
sender, EventArgs e)

**Comment by dahall** [comment]
This is a common, although somewhat cryptic, error that results from the user providing credentials that are either incorrect (bad username, bad username/password combo, incorrect account domain) or that are not acceptable with the current security (restricted account, permissions within task folder, adding a trigger that requires elevated permissions (e.g. logon, startup, event), etc.). For more information on security, please see the Wiki.

**Comment by ajcsoftware** [comment]
Thanks very much for your quick answer.
