### ISSUE TITLE
Windows 10 Task Scheduler Security

### ISSUE THREAD

**Issue by Wardrop** [dahall/TaskScheduler#4]
This isn't strictly related to your library, but perhaps you or other users of this library have run into and know of a solution. It seems under Windows 10, it's no longer possible for an ordinary user to view tasks created by other users or administrators. Under previous versions of Windows, it was possible to modify the ACL's on C:\Windows\System32\Tasks to allow lower privileged users to read and/or modify tasks that they wouldn't otherwise be able to access.

Does anyone know a way around this Windows 10 limitation?

**Comment by dahall** [comment]
Microsoft has tightened security in Windows 10 for all tasks. The C:\Windows\System32\Tasks folder only and exclusively holds V1 (WinXP and before) tasks. If any tasks are created using V2 (Vista and later), their security is defined by methods within the library. See [SetAccessControl](https://dahall.github.io/TaskScheduler/html/M_Microsoft_Win32_TaskScheduler_Task_SetAccessControl.htm).

**Comment by Wardrop** [comment]
Awesome, did the trick! For anyone else who may stumble upon this, here's what I did which gives read access to all authenticated users which is all I needed for this particular circumstance:

``` c#
var task = ts.RootFolder.RegisterTaskDefinition(ScheduledTaskName, td, TaskCreation.CreateOrUpdate, "System", null, TaskLogonType.ServiceAccount);
var taskSecurity = new TaskSecurity();
taskSecurity.AddAccessRule(new TaskAccessRule("Authenticated Users", TaskRights.Read, System.Security.AccessControl.AccessControlType.Allow));
task.SetAccessControl(taskSecurity);
```

Having that documentation online has been really handy also, so thanks again for that.

**Comment by dahall** [comment]
Great code. With your permission, I'd like to include it as the example code for SetAccessControl.

**Comment by Wardrop** [comment]
Yeah of course, go for it 👍
