### ISSUE TITLE
Add an Example for TaskEditDialog Class

### ISSUE THREAD

**Issue by trivikramak** [dahall/TaskScheduler#42]
Please add an example for TaskEditDialog Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://dahall.github.io/TaskScheduler/html/T_Microsoft_Win32_TaskScheduler_TaskEditDialog.htm

**Comment by dahall** [comment]
Please see the Wiki. There are multiple examples there.
