### ISSUE TITLE
Trying to connect to a remote machine but I always have access denied error

### ISSUE THREAD

**Issue by first100** [dahall/TaskScheduler#43]
Hello,
im trying to connect to a remote machine to get all task and im using:
 
`  using (TaskService ts = new TaskService(computer,user,domain,password))
                {
                    EnumFolderTasks(ts.RootFolder);
                }`
but i have this error:
The request is not supported. (Exception from HRESULT: 0x80070032)
or access denied error, but the credentials is right.

Can anyone help me?
Thanks

**Comment by dahall** [comment]
I'd suggest two things:
1) Make sure you have followed the [instructions in the documentation](https://github.com/dahall/TaskScheduler/wiki/TaskSecurity) for opening both sides of the connection.
2) Try using the [TaskSchedulerConfig](https://github.com/dahall/TaskSchedulerConfig) tool I wrote to help troubleshoot this exact kind of scenario. There is a ClickOnce install link at the bottom of the page.

**Comment by first100** [comment]
Thank you for your reply, i have followed the instructions in  documentation and now execute the TaskSchedulerConfig, i trying to enumerate task from local machin with Windows 10 pro to remote machines with win 2003 or win 2008 server. I always has this error "The request is not supported. (Exception from HRESULT: 0x80070032)"

**Comment by dahall** [comment]
Do you get the exception on the TaskService constructor or elsewhere? Also, the WS2003 will always be V1 so you may have more luck by specifying `true` for the forceV1 parameter of the TaskService constructor.

**Comment by first100** [comment]
The exception is in the constructor , i have now tried on Win Server 2012 R2 (with true and then with false) but the error is same .
![capture](https://user-images.githubusercontent.com/3974259/34293684-e08253fa-e705-11e7-97e1-22d351eed9bf.PNG)

Thanks.

**Comment by dahall** [comment]
Are user, domain or password equal to NULL?

**Comment by ChrisonSimtian** [comment]
Hi dahall, I've experienced the same issue as described above .
Your validation tool didnt find any issues and the method gets a valid username together with the correct password.

The lib seems to work fine on machines that dont belong to an active directory domain, but as soon as I try it on a machine that is in a domain, the above error comes up.

Any ideas?

PS: Ive handed over the userId in several variations together with the domains name, none seemed to work. Neither did handing over just the username.

**Comment by dahall** [comment]
When running the Diagnostic tool, make sure you are running "As Administrator" and running on both sides of the connection. There are failures that can only be detected on one side or the other with elevated permissions. You should also, at the end of the first run, click on "Troubleshoot connecting to a remote computer" and go through those steps.

@ChrisonSimtian: I have run this tool in an AD environment for many years. Often there are firewall, access list, or policy problems on one side of the connection.

**Comment by dahall** [comment]
Also, after running the tool, if any of the issues are "Not fixed", you can click on "View detailed information", find the error in question and see if there is "Requires consent" status. If so, you can click on the ">" (Play) button to the far right to fix that error as well.

**Comment by Anastasius80** [comment]
I have the same error on my site. I used the tool (above) and checked all. Everything is ok. 

I used followning command:

 new TaskService($@"\\{HostFqdn}", _adminUsername, _adminDomain, _adminPassword);

I got the error, after that i tried to use following command:

 new TaskService($@"\\{HostFqdn}");

and run the program with "run as" and used the "admin user". Now it works, but i don't want to run the program with the user directly, i want to use the first command. 

Any ideas?

**Comment by dahall** [comment]
@Anastasius80: When running the tool, did you also (at the end) run the "Test Remote Connections" button? Also, did you try running the tool on both the client side host and the remote host?

If so, and they all checked out, then I'm out of ideas. Microsoft has not documented all the conditions that have to be in place for remote connections to work for their underlying ITaskService to connect. The tool tests for all those I have found on my own. I have found, like you, that:
* Connections work best when using the client host token (no username)
* Firewalls cause big problems on the client and remote host
* Connecting from one OS version to another has more problems than connecting from like to like
* User privileges on both sides of the connection play a significant role.

**Comment by Anastasius80** [comment]
@dahall thanks for your response. My solution is now, that i used the client host token:

• Connections work best when using the client host token (no username)

I tested all (both sides) with the tool, and found no errors, every button is clicked :)

Thank you for your help!

**Comment by DaveRothlin** [comment]
Hi, dealing with the same issue when trying to Import Task Schedules in VisualCron. On a Server not running a Firewall it works, but when trying on another one with FRW-enabled i get the mentioned error. Could you eventualy help me with the Ports i Need to open for the Import to work?

**Comment by dahall** [comment]
See https://github.com/dahall/TaskScheduler/wiki/TaskSecurity#Connecting-to-a-remote-server-or-local-server-with-different-credentials

**Comment by Hung-Yang** [comment]
Hello,

thank for you to create this project , and i meet some problem as below.

im trying to connect to a remote machine by same code and same IIS machine as below , and using different version of Task Scheduler, then i get the different response.

**TaskService** ts = _new_ **TaskService**(workstation, userName, domain, password, true);

when using version **2.8.6.0** will get response as incorrect user name or password.

and when i change to version **2.5.28** , then i get the right TaskService back.

But i still want to use the new version, so what can i do to fixed it?

thank you!

**Comment by dahall** [comment]
What are the Windows versions of the two machines?

**Comment by dahall** [comment]
And. what are the Windows versions of the host machines (where the library is executed)?

**Comment by Hung-Yang** [comment]
> 
> 
> What are the Windows versions of the two machines?

Server slite is windows server 2012 R2 and remote site is server 2003
and library used in 2012R2
