### ISSUE TITLE
TaskService call failed sometimes

### ISSUE THREAD

**Issue by nkfeiyang** [dahall/TaskScheduler#44]
Here is my code:
using (TaskService ts = TaskService.Instance)
            {                
                using (var folder = ts.GetFolder(path))
                {                    
                }
            }

However, the GetFolder throw an exception sometimes. I checked the the TaskService object when failed and fount it is not connected. Maybe I call the code two freqently?

How could I make sure it will always work?

**Comment by nkfeiyang** [comment]
I found that if I change the code from TaskService ts = TaskService.Instance to TaskService ts = new TaskService(). It will not fail anymore.

**Comment by dahall** [comment]
You are correct. The `TaskService.Instance` property is just a static instance of TaskService connected locally. By placing that property value in the `using` statement, you are effectively disposing of the static instance. That property is intended to never be disposed. Both of the following will work:
```c#
// Create your own instance of TaskService and use
using (TaskService ts = new TaskService())
{
   var fdr = ts.GetFolder(path);
}
```
```c#
// Use the static instance
var fdr = TaskService.Instance.GetFolder(path);
```
