### ISSUE TITLE
Have just the needed resources through NuGet

### ISSUE THREAD

**Issue by teejay-87** [dahall/TaskScheduler#46]
Hello, I installed just the Main Library through NuGet.

Since this is not a UI one, I just want english resources. Is that possible?

**Comment by dahall** [comment]
The main assembly's default language is English. If you extract all of the NuGet package you could distribute just the primary Microsoft.Windows.TaskScheduler.dll file. That has just the English resources embedded. The other resource assemblies support the natural language trigger and action expressions.

**Comment by teejay-87** [comment]
That's OK, but I don't understand why a non-UI package has multi-language resource file... for exceptions?

**Comment by dahall** [comment]
The ToString() methods for Action and Trigger derivatives generate a natural language description of the action or trigger (e.g. "Every other day at 12:00 pm"). This is where the language assembles are needed. While these are used in the UI, they were part of the native library so were included.

**Comment by teejay-87** [comment]
I understand that, but IMHO, they should not be part of the main library. I think this is purely UI content.
But don't worry, that's just my opinion :smile:

**Comment by GF-Huang** [comment]
Move the `ToString` to the UI Library (or a stand alone nuget package) as Extensions maybe better ?

```cs
public static class Extensions {
    public static string ToString(this Trigger trigger) {
        // ...
    }
}
```

**Comment by dahall** [comment]
@GreatFireWall : What end result are you after so I better understand the value of doing something this disruptive to the current user base?

**Comment by GF-Huang** [comment]
Hi @dahall , it makes the output directory (`xxx\bin\Debug`) a lot of resources folder. Although not a big problem, however, when the programs are packaged into an installation package, it may cause additional filtering to avoid adding these unnecessary dll files. 

This is just my personal needs, but other users may encounter similar problems. :)

![image](https://user-images.githubusercontent.com/4510984/64261227-c6299480-cf5e-11e9-85ad-8deac947fc04.png)

**Comment by teejay-87** [comment]
@dahall It's just cleaner, the source and the result. It's correct that the UI part is in a different library.

@GreatFireWall we are two now ;-)

**Comment by dahall** [comment]
From a pure design standpoint, I totally agree. However, after almost 12 years of the product functioning as is, doing what you suggest would likely cause a scenario that would break a lot of existing code (there are over 2M downloads). Any thoughts on how to accomplish your request and maintain backwards compatibility?

**Comment by GF-Huang** [comment]
Keep the `TaskScheduler` and `TaskSchedulerEditor` not change. 
Add new nuget packages like `TaskSchedulerCore` and `TaskSchedulerLocalization`. 

I can only think of this for the time being.

**Comment by teejay-87** [comment]
@GreatFireWall same opinion.

Honestly, can't help more because I don't know the library in its interior.

**Comment by teejay-87** [comment]
I mean, you continue distributing the final package, that will use sub core-packages (usable standalone).

**Comment by GF-Huang** [comment]
> I mean, you continue distributing the final package, that will use sub core-packages (usable standalone).

Emm, it seems like make `TaskScheduler` depends `TaskSchedulerCore` and `TaskSchedulerLocalization` possible.
