### ISSUE TITLE
The current version of the native library (1.3) does not support the original or minimum version of the ".NET Framework NGEN v4.0.30319" task (1.4/1.4)

### ISSUE THREAD

**Issue by andrewtheart** [dahall/TaskScheduler#47]
When getting the definitions of certain tasks on mostly Windows 2012 servers, I get the following error:

The current version of the native library (1.3) does not support the original or minimum version of the ".NET Framework NGEN v4.0.30319" task (1.4/1.4)

I am running this code on a Windows 7 machine. (Perhaps it needs to be run on a machine with the native library v 1.4 - i.e. a recent server edition of Windows

Any ideas?
Thanks

**Comment by dahall** [comment]
Something is amiss. This message should only appear when connecting to systems with tasks defined for uplevel tasks. From your message, it appears you are viewing downlevel tasks. Any chance you could post the XML of the task you are trying to retrieve? That would go a long way to helping me troubleshoot the problem. The routine that creates that exception is one that pulls the XML from the remote server and tests to see if it contains elements that cannot be handled by the local library.

**Comment by dahall** [comment]
Sorry. I just re-read your message and Windows 2012 _is_ uplevel from Windows 7. This is the root of your problem. Windows 8/Server 2012 introduced a number of new items to tasks that cannot be understood by Windows 7. See the documentation for the TaskCompatibility enum in [Task.cs](https://github.com/dahall/TaskScheduler/blob/master/TaskService/Task.cs) for details of what's been added with each release.
