### ISSUE TITLE
DeleteExpiredTaskAfter error

### ISSUE THREAD

**Issue by peladam** [dahall/TaskScheduler#48]
I am trying to create a task that runs a cmd and after it's done (+ 5 minutes) it deletes itself. If I set up the task without td.Settings.DeleteExpiredTaskAfter and wihtout tt.EndBoundary. It works just fine. Do you have any ideas what I did wrong or what am I missing? 
**The error I'm getting is "(35,4):EndBoundary:".**

Here is my function
``` c#
private void createTask(DateTime dateAndTime, string username, string groupName, string computer_name)
{
	using (TaskService ts = new TaskService(computer_name))
	{
		TaskDefinition td = ts.NewTask();

		TimeTrigger tt = new TimeTrigger();
		tt.StartBoundary = dateAndTime;
		tt.EndBoundary = dateAndTime + TimeSpan.FromMinutes(5);
		
		td.Settings.StartWhenAvailable = true;
		td.Settings.Hidden = true;
		td.Settings.ExecutionTimeLimit = TimeSpan.FromMinutes(10);
		td.Settings.DeleteExpiredTaskAfter = TimeSpan.FromMinutes(1);
		td.Settings.DisallowStartIfOnBatteries = false;

		string parametr = "/c net localgroup " + groupName + " /delete " + username;
		td.Actions.Add(new ExecAction("cmd.exe",parametr, null));

		ts.RootFolder.RegisterTaskDefinition(@"Automatic Membership Validation", td,
		TaskCreation.CreateOrUpdate,"SYSTEM",null,TaskLogonType.ServiceAccount);
	}
}
``` 
This is how I call the function
``` c#
createTask(dateTimePicker1.Value, "testuser", "Administrators", "testcomputer");
``` 
In all cases dateTimePicker is set-up like this:
``` c#
dateTimePicker1.Format = DateTimePickerFormat.Custom;
dateTimePicker1.CustomFormat = "dd'.'MM.yyyy - HH':'mm";
```

**Comment by dahall** [comment]
The TimeTrigger, given that it only executes once, does not support using EndBoundary. Just remove that line and leave the rest and it should all work.

**Comment by peladam** [comment]
So i removed this line, but I got the same error.
tt.EndBoundary = dateAndTime + TimeSpan.FromMinutes(5);

When I recreated the same task in Task Scheduler in Windows I got error saying that I need to add at least one Trigger event with expriation date (that is EndBoundary if I get this correctly).

**Comment by dahall** [comment]
Simple coding problem: You must add the trigger to the definition.
```
td.Triggers.Add(tt);
```

**Comment by peladam** [comment]
Thank you!
