### ISSUE TITLE
.NET Framework NGEN v4.0.30319 "error"

### ISSUE THREAD

**Issue by Anastasius80** [dahall/TaskScheduler#50]
Hello,

ich want to connect from a 2016 Server to a win10 Client (remote) and read all Tasks.

I used:

var x = new TaskService($@"\\{Host}", _username, _domain, _password);
....

i got the error:
The current version of the native library (1.5) does not support the original or minimum version of the ".NET Framework NGEN v4.0.30319" task (1.6/1.6)

does anyone have a tip for me? 

Thanks

**Comment by dahall** [comment]
Yes. You cannot connect to an upstream system (new OS) and read all tasks. New features are introduced in almost each new Windows version and it makes reading them from older clients impossible. To ensure you can read all tasks, use a client from the same or newer Windows version.

**Comment by Anastasius80** [comment]
thanks
