### ISSUE TITLE
RunEx: NullReferenceException with "parameters" parameter null

### ISSUE THREAD

**Issue by fowl2** [dahall/TaskScheduler#51]
Hi, 

First of all, thanks for this project.

The RunEx method takes a "parameters" parameter string[], but crashes if it's null. If you've read the documentation for RegisteredTask.RunEx this is very confusing, as null is a valid value (meaning "no parameters).

Here's the first line that uses the parameter without checking it for null: https://github.com/dahall/TaskScheduler/blob/2b2e8eb9932fac8111d4021bf348eb1c2125acd2/TaskService/Task.cs#L1292

Thanks again!

**Comment by dahall** [comment]
The RunEx method uses a `params` parameter for the last argument that accepts 0 or more strings. If you are passing `null` then you are effectively passing it as the first string value parameter, which is not valid. I have put in some error checking to check for that condition and provide a more descriptive exception.
