### ISSUE TITLE
RunningTask.Refresh() throws exception on on task completion

### ISSUE THREAD

**Issue by fowl2** [dahall/TaskScheduler#52]
Might be nice to note this in the documentation :=)

> System.Runtime.InteropServices.COMException (0x8004130B): There is no running instance of the task. (Exception from HRESULT: 0x8004130B)
>    at Microsoft.Win32.TaskScheduler.V2Interop.IRunningTask.Refresh()

https://github.com/dahall/TaskScheduler/blob/2b2e8eb9932fac8111d4021bf348eb1c2125acd2/TaskService/Task.cs#L891

**Comment by dahall** [comment]
This is a bit obscure. I have updated this method so that it will throw an `InvalidOperationException` if the task is not running any longer and have updated the method's documentation.
