### ISSUE TITLE
Localization to Russian

### ISSUE THREAD

**Issue by shuya-razbor** [dahall/TaskScheduler#54]
Hello!
First of all let me thank you for such an amazing piece of work. 
And I'm sorry for opening a new issue due to my only personal small need.
So would you mind helping me with localization to Russian language?
What exactly I need to be localized is TaskEditDialog and all information related to trigger descriptions. 

BUT! There is one more problem. I am not able to build this project on my own because of lower VS version than required. 
Is there any chance of you providing me with rebuilt dll after I prepare aforementioned translations?

**Comment by dahall** [comment]
Attached to this message is an Excel spreadsheet [TaskSched.2018_03_03.xlsx](https://github.com/dahall/TaskScheduler/files/1777615/TaskSched.2018_03_03.xlsx) with all the resource strings translated into the different languages. For the Russian translation in column ".ru", please add or correct each entry giving special attention to those strings in English that have format specifiers (e.g. {0}, {1} etc.) or that have an embedded '&' character to specify the keyboard shortcut or that use special characters (<xx> or x->). The automated Azure translator usually messes those up and it appears to have added an '!' in many places. I would recommend using the Windows Task Scheduler tool as your guide for wording. The other localizations have copied it where possible for consistency. Microsoft has a [search engine](https://www.microsoft.com/en-us/language/Search) for localized phrases in Windows. If the cell is red, ignore it.  Once done, post it here with your reply. I will then rebuild the project and release a new version with the new localization.

**Comment by shuya-razbor** [comment]
Well I guess I've done everything I could. 
[TaskSched.2018_03_03.xlsx](https://github.com/dahall/TaskScheduler/files/1782077/TaskSched.2018_03_03.xlsx)

**Comment by dahall** [comment]
I have code for you to test included in these 2 zip files. Replace the files in your build directory with these and relaunch your application. They include the Russian resource assemblies.
* [TaskScheduler.zip](https://github.com/dahall/TaskScheduler/files/1783153/TaskScheduler.zip)
* [TaskSchedulerEditor.zip](https://github.com/dahall/TaskScheduler/files/1783154/TaskSchedulerEditor.zip)

Let me know if there are any changes that need to be made. Once complete, I'll release this new version.

**Comment by shuya-razbor** [comment]
Thanks for the dlls. Almost everything seems fine, I've just added some small corrections. Here's the updated version: 
[TaskSched.2018_03_03.xlsx](https://github.com/dahall/TaskScheduler/files/1787535/TaskSched.2018_03_03.xlsx) 
A little upset though that not all the tabs of TaskOptionsEditor are localized. Really like the design of it. Gotta switch back to the standard look of TaskEdit. Anyway it's just a minor inconvenience so thanks again for your help.

**Comment by dahall** [comment]
I found the problem with TaskOptionsEditor. If possible, would you fill in the items in this spreadsheet that are yellow?
[TaskSched2018_03_06.xlsx](https://github.com/dahall/TaskScheduler/files/1787766/TaskSched2018_03_06.xlsx)

**Comment by dahall** [comment]
Thank you. Your changes will be available in the next few days in the next release.
