### ISSUE TITLE
End/Disable Task?

### ISSUE THREAD

**Issue by yutzuch** [dahall/TaskScheduler#6]
Hi!
How can I end or enable/disable a specific task?
I know the way to remove(ts.RootFolder.DeleteTask("Taskname");) it but I just want to end or disable it.

**Comment by saucepleez** [comment]
You can do something like this:
```cs
using (TaskService ts = new TaskService())
{
   //disable task
   var taskToDisable = ts.FindTask("Some_Task_Name");
   taskToDisable.Enabled = false;
}
```

**Comment by yutzuch** [comment]
@jason-not-json Thank you! It does works.

**Comment by dahall** [comment]
Thanks @jason-not-json. The Enabled property does the work. If you know which folder the task is in, and are using the default parameters for connecting to the TaskService instance, you can also access the task as follows:
```cs
var task = TaskService.Instance.RootFolder["Some_Task_Name"];
if (task != null)
   task.Enabled = true;
```
Given that tasks can be deleted, the error checking is a good idea.

**Comment by saucepleez** [comment]
Great work on this library!
