### ISSUE TITLE
Cron expression evaluation is incomplete

### ISSUE THREAD

**Issue by jazmatician** [dahall/TaskScheduler#61]
Granted, the comments in the code warn of this, but some basic expressions seem to have incorrect interpretations -- 
*/15 * * * * should be interpreted as "every 15 minutes" but returns a not-implemented exception.
likewise for alternate expressions with the same meaning: 0-59/15 * * * * and 0,15,30,45 * * * * 
Reporting this as a bug as this expression, 0/15 * * * * which should mean every fifteen minutes starting at midnight is instead interpreted as "every hour, at midnight." 
Another issue is with commas, i.e. 0 0,12 * * * (midnight & noon daily) which seem to throw the whole interpreter out the window. A job is created with no trigger at all.

**Comment by dahall** [comment]
Thanks for being the first user to ever, in 15 years, report a problem with the cron parsing. It is possible you are the first person to use it given the magnitude of the problem. I'm correcting it and will have these errors fixed in the next release.

**Comment by jazmatician** [comment]
I'm glad you can fix it, because I'm just using cron for the first time, so I had a hard time working through the parsing to fix it myself.
Hey, it's nice to know your code is being used, right? :)

**Comment by dahall** [comment]
This now fixed in the code and will be in the next release 2.8.1
