### ISSUE TITLE
Can't add a task when using TaskLogonType.InteractiveToken for AD account

### ISSUE THREAD

**Issue by bob53050** [dahall/TaskScheduler#62]
Hello all,

I can add the task when testing on system using a local login and the TaskLogonType.InteractiveToken option but not for a domain account (Active Directory) account that is currently logged into.

Please advise when you get a chance.

Thanks for your help,

Bob

**Comment by dahall** [comment]
If you are using InteractiveToken, it is irrelevant how you are logged in. It should be noted that all accounts require certain system privileges to create tasks. For more information, see the [Security Wiki Page](https://github.com/dahall/TaskScheduler/wiki/TaskSecurity) for detail and links.

**Comment by bob53050** [comment]
Thanks for your reply David :)
