### ISSUE TITLE
cannot creating a task without running app as admin

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#621]
when trying to create tasks I get access denied unless the program is stated as admin.  the user is a local admin on the system, the task is being created on the same system, and the task is to be run as a different user.  below is the gist of the code, please let me know   

    using (TaskService ts = new TaskService())
    {
               TimeTrigger start = new TimeTrigger { StartBoundary = dateTime1.Value };
                TaskDefinition td = ts.NewTask();
                td.Triggers.Add(start);
                td.Principal.RunLevel = TaskRunLevel.Highest;
                td.Settings.Compatibility = TaskCompatibility.V2_2;
                td.Actions.Add(new ExecAction(Environment.GetCommandLineArgs()[0], cmd, null));
                ts.RootFolder.RegisterTaskDefinition(&quot;Task Name&quot;, td, TaskCreation.Create, username, password, TaskLogonType.Password);
    }

any ideas?  

Originally posted: 2015-05-06T22:57:27

**Comment by dahall** [comment]
The code calling the TaskService constructor must be running as Administrator to avoid UAC blocks. The security rights of the TaskService instance will determine if the RegisterTaskDefinition method can be called. Registering a task as a specific user instruct that task to run as that user.  


Originally posted: 2015-05-10T13:29:36

**Comment by coultonluke** [comment]
@dhall Thanks for taking the time to comment on this.  We're running into the same issue where we are running an application as a scheduled task on Windows Server 2016.  Really we wanted to avoid running the application as Administrator.  I don't suppose you know which UACs could be blocking it?  We've tried enabling and disabling each one and then all in the list in `Local Security Policy` > `Local Policies` > `Security Options` but to no avail.

Is there a way to do it without assigning Administrator permissions?

**Comment by dhall** [comment]
cc @dahall :)

**Comment by dahall** [comment]
Please review https://github.com/dahall/TaskScheduler/wiki/TaskSecurity and the MSDN links on that page for more ideas.
