### ISSUE TITLE
How do I check for a certain task name?

### ISSUE THREAD

**Issue by ghost** [dahall/TaskScheduler#65]
Hey,
I've been using this library and it's great.

I want to ask how do I find a task on Scheduler Task (from Windows).
I'm looking for a method, property, soemthing to find a task that I add called "MySQL backup (dbName)". Thanks.

**Comment by dahall** [comment]
```cs
var myTask = TaskService.Instance.FindTask("MySQL backup (dbName)");
if (myTask == null) throw new ArgumentException();
```

**Comment by ghost** [comment]
Thanks :+1:
