### ISSUE TITLE
Setting Task Description: new line carriage return ignored.

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#653]
When setting task description text, vbCrLf is ignored.   
How can we specify that a new line should start?  

Originally posted: 2015-12-24T09:28:03

**Comment by dahall** [comment]
I'm not sure what vbCrLf translates to in a string. However, I do know that in C# one can add new lines by putting in the "\r\n" combination. For example, the following code works:  
```cs
td.RegistrationInfo.Description = "1) Line 1\r\n2) Line 2";
```

Originally posted: 2015-12-24T15:35:23

**Comment by dahall** [comment]
in vb.Net **vbCrLf** is the equivalent to  **\r\n**  (Carriage Return + LineFeed).  
Did you test the effect of using \r\n ?  


Originally posted: 2015-12-24T16:01:11

**Comment by dahall** [comment]
Tried environment.newline instead of vbCrLf.  But it still doesn't result in a new line inside the description.  


Originally posted: 2015-12-25T06:23:29

**Comment by dahall** [comment]
Thanks for pointing out how this works as it has helped me find a bug. For some reason, the native Microsoft 2.0 library will strip out the CR value from the string after registering a RegistrationInfo.Description or a RegistrationInfo.Documentation value with a CRLF value in it. The native windows multi-line textbox, expects a CRLF to display multiple lines. I have added code to correct for the native error for those two items and it will appear in the next release.  


Originally posted: 2015-12-26T14:05:43

**Comment by jeanmarc3** [comment]
I have the same issue in v2.8.6 (2018/12/19).  Does anyone know when the fix will be included?
Thx

**Comment by dahall** [comment]
@jeanmarc3 Can you tell me if you are just using code to create the task of if this happens when using the UI editor?

**Comment by jeanmarc3** [comment]
I am using the code:
```cs
TaskDefinition taskDef = ts.NewTask();
taskDef.RegistrationInfo.Description = "Line1" + Environment.NewLine + Environment.NewLine + (char)10 + (char)13 + "Line2";
```
Thx

**Comment by dahall** [comment]
What value are you getting after registering (i.e. what exactly is getting lost)? Thanks for the detail.

**Comment by dahall** [comment]
Here's the code and results I get with the current NuGet package:
```cs
ts.RootFolder.DeleteTask("Test", false);
var td = ts.NewTask();
var txt = "Line1" + Environment.NewLine + Environment.NewLine + (char)10 + (char)13 + "Line2";
output.WriteLine("Orig: " + Regex.Escape(txt));
td.RegistrationInfo.Description = txt;
output.WriteLine("Assigned: " + Regex.Escape(td.RegistrationInfo.Description));
td.Actions.Add("cmd", null, null);
var t = ts.RootFolder.RegisterTaskDefinition("Test", td);
output.WriteLine("Registered: " + Regex.Escape(t.Definition.RegistrationInfo.Description));
```
Results:
```
Orig: Line1\r\n\r\n\n\rLine2
Assigned: Line1\r\n\r\n\r\n\rLine2
Registered: Line1\r\n\r\n\r\n\r\nLine2
```
Will you confirm this is what you're seeing?

I'll work on this for the next release. I don't have a time-frame for it yet.

**Comment by dahall** [comment]
I have updated the code so that it will consistently convert all standalone LF to CRLF, all standalone CR to CRFL, and leave all CRLF as they are. Effectively, your string above would translate into "Line1\r\n\r\n\r\n\r\nLine2" as it would leave the first two NewLine values alone and the convert both the \n and the following \r to NewLine values as well. I cannot find an instance, using the current NuGet package on any Windows version, where NewLine is replaced with nothing. My goal was to ensure that the value pre-registration and post-registration matched. Given that the base library converts either \n or \r standalones to \n, it is the best I can do.
