### ISSUE TITLE
Run event with computer being turned off.

### ISSUE THREAD

**Issue by ghost** [dahall/TaskScheduler#66]
hey again,
Please, can you tell me whats the code to add a event to Scheduler Task but made that event run even if computer is turned off?

thanks.

**Comment by dahall** [comment]
`TaskDefinition.Settings.WakeToRun = true`
I'd also set, `TaskDefinition.Settings.StartWhenAvailable = true` too just in case it can't wake up.

**Comment by ghost** [comment]
Thank you.
