### ISSUE TITLE
Synchronize across time zones

### ISSUE THREAD

**Issue by naasking** [dahall/TaskScheduler#67]
Related to issue #26, I can't see to find an option to control the trigger flag "Synchronize across time zones".

I had the thought that perhaps the DateTimeKind option of DateTime controlled that, but it had no effect. Does this option exist?

It looks like it is possible with schtasks.exe: https://stackoverflow.com/a/49542203/144873

**Comment by dahall** [comment]
Checking the "Synchronize..." check box will force an "Unspecified" DateTime value to a UTC value. If the DateTime value is either "Local" or "UTC", then it should be checked already. Setting the StartBoundary to a DateTime with Kind = "Unspecified" will leave the checkbox unchecked.

**Comment by naasking** [comment]
But Local should have the same behaviour as Unspecified. If I want something to run at 8 AM local time, but Local checks "synchronize across time zones" as you say, then this does not always run at 8 AM local time but changes +/- 1 hour with daylight savings. This is what I tried initially as the obvious solution.
