### ISSUE TITLE
Remove JetBrains dependency.

### ISSUE THREAD

**Issue by Fungusware** [dahall/TaskScheduler#7]
The latest version of the NuGet package has a dependency on JetBrains.Annotations (>= 11.0.0)

Can this be removed, it seems unnecessary.

**Comment by dahall** [comment]
It is being used to improve the development experience for those using JetBrains Resharper. I'll look at how I can remove the NuGet package dependency.

**Comment by dahall** [comment]
I have removed it and it will be adjusted in the next release (2.6.2)

**Comment by Fungusware** [comment]
Perfect, thank you and keep up the excellent work!
