### ISSUE TITLE
How can I add Run whether user is logged on or not to my application

### ISSUE THREAD

**Issue by dahall** [dahall/TaskScheduler#705]
Hello,  
  
I have an application that creates a scheduled task, but the program it is using it needs, to run whether user is logged on or not.  
  
I have done a lot of research and tried many things, but cannot seem to get this working.  
  
Can someone please help me.  
  
Thanks,  

Originally posted: 2016-06-03T10:52:33

**Comment by dahall** [comment]
An Administrator may register a task to run as the SYSTEM account or any user can register a task as any user and supply a password. The first option cannot access the network and the second option will only be able to run a task the requires the rights of the supplied user. See the [Security Page](https://taskscheduler.codeplex.com/wikipage?title=TaskSecurity) for examples.   


Originally posted: 2016-06-04T14:12:30

**Comment by dahall** [comment]
Hi Dahall,  
  
So I'm not seeing where i can use the Run whether user is logged on or not.  
  
What I can do is set the Run with TaskRunLevel.Highest, but this did not work.  
  
Running it as an Administrator did not work, if I logged out of the server.  
  
I looked a the Security page, I did not see anything related to what I need, can you please help me find the correct code.  
  
Thanks,  
  
-Mike  


Originally posted: 2016-06-07T09:21:45

**Comment by Shakebag** [comment]
I'm having the same issue and I cannot find anywhere that has this figured out.  I just want to create a daily trigger task that does not require the user to be logged in, but no matter how I create it, It says it will only run when the user is logged in.

**Comment by dahall** [comment]
This is achieved using the `TaskFolder.RegisterTaskDefinition` with the username param set to the user and the logonType param set to `TaskLogonType.S4U`.
