### ISSUE TITLE
Is this creating language subfolders, and can I turn that off?

### ISSUE THREAD

**Issue by dlwiii** [dahall/TaskScheduler#760]
I'm using this from nuget, and think that it is causing a number of subfolders to appear: de, es, fr, it, and zh-CN, each with a Microsoft.Win32.TaskScheduler.resources.dll file.

This is an internal app, no need for language support.  How do I turn this off?

**Comment by dahall** [comment]
You can't "turn it off" per se, but you can just delete those folders before deployment and only the English resources would then be used.
