### ISSUE TITLE
Impossible to use IReadOnlyList<T>

### ISSUE THREAD

**Issue by DamirAinullin** [dahall/TaskScheduler#761]
After adding TaskScheduler Nuget package I can't use  IReadOnlyList<T> from standard .NET library and see the next error in my code:

`
The type 'IReadOnlyList<T>' exists in both 'Microsoft.Win32.TaskScheduler, Version=2.8.1.0, Culture=neutral, PublicKeyToken=c416bc1b32d97233' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
`

.Net Framework 4.5, version of TaskScheduler Nuget package 2.8.1.

**Comment by DamirAinullin** [comment]
Thanks for reply. Yes, and also we can use extern alias on mscorlib like it is descrbied [here](https://stackoverflow.com/questions/27589528/how-to-create-an-extern-alias-to-mscorlib#)
But I don't think it is a good idea to add public classes from standard library with the same namespace to Nuget package. I suppose you did it on purpose to have compatibility with old versions of .NET Framework. Maybe right solution is to have version of dll in Nuget-package, for .NET Framework 4.5 too.

**Comment by dahall** [comment]
It is for compatibility. The NuGet package already includes builds for 2.0, 3.5, 4.0 and 4.5.2. It was built against 4.5.2 rather than 4.5 as many organizations require the fully patched version of 4.5 (which is 4.5.2) and is Microsoft's recommendation.

**Comment by dsingh-deep** [comment]
Hi. Till now I was using my application (.Net 4.6.1 ) with 2.8.12 version.  After upgrading to Scheduler 2.8.15 I keep getting the compiler error! 

> The type 'IReadOnlyList<T>' exists in both 'Microsoft.Win32.TaskScheduler, Version=2.8.15.0, Culture=neutral, PublicKeyToken=c416bc1b32d97233' and 'mscorlib, Version=4.0.0.0 ...

Please let me know how to get past this error without re-targeting my existing project! Thanks.

**Comment by dahall** [comment]
IReadOnlyList is only included in the .NET 2.0, 3.0 and 4.0 builds for backwards compatibility. My guess is that somehow, when Visual Studio unpacked your update, something went wrong and the incorrect build got associated with your project. I would remove the NuGet package from your package and re-reference it to see if the error goes away. I have a .NET 4.7.2 project building against this library without the error and it should be working the same.

**Comment by dsingh-deep** [comment]
@dahall : Re adding the nuget package helped. Thanks a ton.

**Comment by kaizenn17** [comment]
![Sin título](https://user-images.githubusercontent.com/72838146/95924306-bb5e4780-0d8d-11eb-97df-57912e2208ae.jpg)

buenas, tengo este problema, la verdad que no se como solucionarlo, si alguien me pudiera ayudar seria lo mejor, no instale nada, no hice nada, un dia encendi la pc y aparecio esto y no se como hacer que deje de aparecer

**Comment by dahall** [comment]
@kaizenn17 Some application is likely using this library to maintain system tasks. Under "Details", determine the calling application and report the error to them.

**Comment by kaizenn17** [comment]
como podria hacer eso? es que soy un usuario convencional, no se tanto de como encontrar la aplicacion que utiliza la biblioteca

**Comment by dahall** [comment]
The next time the error occurs, expand the Details button and copy the text and paste it here. I may be able to help you determine the application. If not, this forum is for technical developers and is not a support forum.

**Comment by kaizenn17** [comment]
Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.IO.FileNotFoundException: No se puede cargar el archivo o ensamblado 'Microsoft.Win32.TaskScheduler, Version=2.8.20.0, Culture=neutral, PublicKeyToken=c416bc1b32d97233' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.
Nombre de archivo: 'Microsoft.Win32.TaskScheduler, Version=2.8.20.0, Culture=neutral, PublicKeyToken=c416bc1b32d97233'
   en werer.Form1.Form1_Load(Object sender, EventArgs e)
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Form.OnCreateControl()
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.Form.WmShowWindow(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

AVS: El registro del enlace de ensamblado está desactivado.
Para habilitar el registro de errores del enlace de ensamblado, establezca el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Nota: existe una disminución del rendimiento asociada registro de errores del enlace de ensamblado.
Para desactivar esta característica, elimine el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog].



************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4250.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
werer
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base: file:///C:/Windows/Temp/werer.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4250.0 built by: NET48REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4200.0 built by: NET48REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4220.0 built by: NET48REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.3752.0 built by: NET48REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

es esto lo que me aparece, perdon por molestar pero yo no entiendo nada del tema

**Comment by dahall** [comment]
It appears the calling application is `C:\Temp\werer.exe`. From an internet search, it appears to be malware. I don't know what it does or how it got on your system. Hopefully that is enough information for you to get to the next step. I have no other help I can offer. Good luck!

**Comment by kaizenn17** [comment]
muchas gracias!!

**Comment by kaizenn17** [comment]
vine a decir que ya elimine el troyano, lo borre y elimine por cmd, muchas gracias!! sos un idolo!!
