### ISSUE TITLE
dll not found in installdir

### ISSUE THREAD

**Issue by Torchok19081986** [dahall/TaskScheduler#762]
Hallo . I tried to create my first Task in TaskScheduler and as reference i used Simple Task Creation as example. I alsways got Microsoft.Win32.TaskScheduer.dll  Missing Execption.
Package was installed via Nuget Command. Can anyone help me with this problem ?

**Comment by dahall** [comment]
Make sure you've installed https://www.nuget.org/packages/TaskScheduler and not the editor.

**Comment by dahall** [comment]
The package supports either .NET 2.0, 3.5, 4.0 or 4.5.2.

**Comment by Torchok19081986** [comment]
Thanks for help. Any support for later Versions of .NET Framework like 4.6 or better ?

**Comment by dahall** [comment]
Not yet, but they would be very simple to add. Please submit an issue with the specific enhancement request.
