### ISSUE TITLE
How get of state of Task ?

### ISSUE THREAD

**Issue by kiquenet** [dahall/TaskScheduler#763]
How check the state ?

I have Task scheduler Windows. I have view the history (ID of events)

One day execution OK
129 Proceso de tarea creado
100 Tarea iniciada
200 Acción iniciada
201 Acción completada
102 Tarea completada

One day execution KO
129 Proceso de tarea creado
100 Tarea iniciada
200 Acción iniciada

322 Solicitud de inicio pasada por alto. La instancia ya se está ejecutando

**Comment by dahall** [comment]
Error 322 indicates that the task's last execution is still running. You can get a list of running tasks from TaskService.GetRunningTasks. You can also query the state of single task by calling TaskService.GetTask(taskName) and then using the result to get the State property. If state is Running, then you will see error 322 if you try to run it again.
