### ISSUE TITLE
Run after RegisterTaskDefinition

### ISSUE THREAD

**Issue by kostazol** [dahall/TaskScheduler#768]
Hello. I found some bug:
When i Create or Update Task:
if StartBoundary != DateTime.Now after  RegisterTaskDefinition new or Updated task Rund. After this running task use Trigger settings.
If StartBoundary == DateTime.Now, then it work correctly and task will run using trigger settings.

**Comment by dahall** [comment]
Will you provide all the settings you have made to the task?

**Comment by kostazol** [comment]
using (TaskService ts = new TaskService())
                    {
                        TaskDefinition td = ts.NewTask();
                        DailyTrigger tt = new DailyTrigger { DaysInterval = 1 };
                        tt.Repetition.Interval = TimeSpan.FromHours(1);
                        tt.StartBoundary = DateTime.Now.Date.AddDays(-1).AddHours(1).AddMinutes(0);
                        td.Triggers.Add(tt);
                        td.Settings.WakeToRun = true;
                        td.Settings.DisallowStartIfOnBatteries = true;
                        td.Settings.StopIfGoingOnBatteries = true;
                        td.Actions.Add(new ExecAction(AppDomain.CurrentDomain.BaseDirectory + "Test.exe", "0", null));
                        ts.RootFolder.RegisterTaskDefinition("Test", td);
                    }

i try to set datetime in feature in tt.StartBoundar, but it also run Task after RegisterTaskDefinition.
If i use " t.StartBoundary = DateTime.Now; " or don't use this setting Task will not run after RegisterTaskDefinition.

**Comment by kostazol** [comment]
Now, I made this:
```
    using (TaskService ts = new TaskService())
                {
                    TaskDefinition td = ts.NewTask();
                    DailyTrigger tt = new DailyTrigger { DaysInterval = 1 };
                    tt.Repetition.Interval = TimeSpan.FromHours(1);
                    tt.StartBoundary = DateTime.Now.Date.AddDays(-1).AddHours(1).AddMinutes(0);
                    td.Triggers.Add(tt);
                    td.Settings.WakeToRun = true;
                    td.Settings.Enabled = false;
                    td.Settings.DisallowStartIfOnBatteries = true;
                    td.Settings.StopIfGoingOnBatteries = true;
                    td.Actions.Add(new ExecAction(AppDomain.CurrentDomain.BaseDirectory + "Test.exe", "0", null));
                    ts.RootFolder.RegisterTaskDefinition("Test", td);
                    ts.GetTask("Test").Enabled = true;
                }
```
I create Task as Disabled Task, and after creation i enable Task.

**Comment by kostazol** [comment]
After some additional test i found that previous  solution also not work. When i made it, i saw this picture:
1) Task was created;
2) Task was enabled. Time of next running is 10:44, now 10:40. 
3) Now 10:45, Time of next running 11:44, time of previous running not change. And also there is not new actions in log.

**Comment by kostazol** [comment]
I have some news, It works correct:
1) i created task with DailyTrigger StartBoundary  = 12.06.2018 14:44, Repetition.Interval = 1 hour
it was disabled while task was creating, and task was enabled after creating. (As i wrote before)
2) Task is not running while time was less than 13.06.2018 14:44. 

Also when i started issue i didn't understand why task run itself after creating. The running after creation is necessary if (StartBoundary  < Datetime.Now) because time of running was in past  and Repetition.Interval willn't work before the first running of task.
The windows UI Task Scheduler works the same as this library.
 
Issue is finished, thank you.
