### ISSUE TITLE
Can TaskSchedule trigger a function 

### ISSUE THREAD

**Issue by kenchu1178** [dahall/TaskScheduler#769]
Is it possible to trigger a function at 18:00 everyday

**Comment by dahall** [comment]
Adding a DailyTrigger with Interval set to 1 and StartBoundary set to 18:00 will trigger. As to a 'function', not directly. You will need to create an executable that can be run, call a PowerShell or command-line script, or create a DLL using my project template at https://github.com/dahall/ITaskHandlerTemplate to house a function.
