### ISSUE TITLE
Task doesn't run

### ISSUE THREAD

**Issue by Peter13434** [dahall/TaskScheduler#770]
I tried a lot of possible combinations to my code but they all just "add" it to task scheduler, but it never executes.

PLEASE NOTE: My application is always running with admin rights, possibly a reason why it doesnt execute?

My current code:
`Private Sub Runatstartup()
        Dim savepath2 As String = Application.UserAppDataPath & "\bootfile.log"
        Using tService As New TaskService()

            Dim tDefinition As TaskDefinition = tService.NewTask
            tDefinition.RegistrationInfo.Description = "My programs startup entry"

            Dim bt As BootTrigger = New BootTrigger()
            bt.Delay = TimeSpan.FromSeconds(10)

            tDefinition.Triggers.Add(bt)

            tDefinition.Actions.Add(New ExecAction(Application.ExecutablePath(), savepath2))

            tService.RootFolder.RegisterTaskDefinition("My program", tDefinition)

        End Using
    End Sub`

Does anyone know what the issue is?

**Comment by dahall** [comment]
As coded, this will only execute 10 seconds after the system starts and only if the user at registration time has admin rights. When do you want it to run?

**Comment by dahall** [comment]
The Event Viewer application has a log that keeps a detailed activity of Task Scheduler. That is where I'd suggest you look next. Looking at the code, I can't see anything wrong.

**Comment by Peter13434** [comment]
The log didn't gave me any information but what I did do is I modificated the current entry in Task Scheduler and replaced the path to my .exe with a non-admin program and it worked! 

Then I checked the box "Run with highest priviliges" in Task Scheduler and it ran fine(with my own admin needed program). So I really need that option checked. Do you know how to?

Option I mean [https://www.digitalcitizen.life/sites/default/files/img/task_scheduler_uac/ts_uac1.png](url)

**Comment by dahall** [comment]
TaskDefinition.Principal.RunLevel = TaskRunLevel.Highest

**Comment by Peter13434** [comment]
Thanks, it works when I edit the entry Trigger to a certain time but whenever I boot/restart it gives me an error code in the Task Scheduler: you don't have permission to perform the requested operation 0x800702E4.

So it works fine when logged in, but it throws an error(not enough permission) when booting? Any idea how to fix it?

**Comment by dahall** [comment]
Permission on executable file?

**Comment by Peter13434** [comment]
Permission is okay, I've found an answer online which seems to work.

Solution seems to be running when the user is logging in (not booting)

So last question then, how do you select: run when user is logging in?
.................................................................................(instead of run when booting)

EDIT: Logontrigger probably, testing now

**Comment by Peter13434** [comment]
Works, thanks for the help

**Comment by dahall** [comment]
If you want to use LogonTrigger for a specific user, you need to specify the UserID property of the LogonTrigger instance.
