### ISSUE TITLE
"Access is Denied" when deleting Task or Folder

### ISSUE THREAD

**Issue by joverton33** [dahall/TaskScheduler#771]
Help Wanted...

I am using the library to connect to the Task Scheduler on localhost, using:
TaskService ts = new TaskService();

I am able to create new tasks and edit tasks. When creating tasks, I am able to create a new folder for a task by using the name "NewDir\new task name".  My problem is when I tried and delete a task or a folder, I seem to sometimes get the error "Access is denied.", but not always.  If I exit my program and run the Windows Task Scheduler, I can always delete the task and the folder.

To delete the task, I am using:
tf.DeleteTask("new task name")
Where tf is a TaskFolder for "NewDir"

To delete the folder, I am using:
tf.DeleteFolder("NewDir")
Where tf is a TaskFolder for the parent directory of NewDir.

Any suggestions for how I can further debug what is happening?

Thanks,

John

**Comment by dahall** [comment]
My first suggestion is to always check to make sure the code is running without UAC (Admin mode). Try right-clicking on the executable and selecting "Run as administrator".
