### ISSUE TITLE
FromCronFormat returns incorrect triggers

### ISSUE THREAD

**Issue by SebastiaanPolfliet** [dahall/TaskScheduler#772]
Hi 

I'm having some troubles with the cron to trigger feature. 

If you use the following statement: 

`Trigger.FromCronFormat("0 0 * * 3");`

You get two triggers: 

0: At 00:00 on every Wednesday each every month, starting 07/16/2018
1: At 00:00 every day

The second trigger is incorrect imho.

The same bug is reproducible if you do: 

`Trigger.FromCronFormat("0 0 * 1-12 3");`

However if you change the cron expression to: 
`Trigger.FromCronFormat("0 0 * 1,2,3,4,5,6,7,8,9,10,11,12 3");`

You get only the one you need: 

0: At 00:00 on every Wednesday each every month, starting 07/16/2018

Can you look into this? Thanks a lot!

**Comment by dahall** [comment]
Fixed in 2.8.2
