### ISSUE TITLE
Cron MonthlyDOWTrigger on Windows 10/Windows Server 2016

### ISSUE THREAD

**Issue by SebastiaanPolfliet** [dahall/TaskScheduler#774]
Hi

When registering a Task Definition with a MonthlyDOWTrigger on Windows 10 (also on Windows Server 2016), with WeeksOfMonth equal to AllWeeks the trigger changes to First/Second/Third/Fourth. This happens when creating the WeeksOfMonth with Trigger.FromCronFormat. Creating the MonthlyDOWTrigger directly (just calling the constructor) is working correctly. 

Following code illustrates the problem: 

```  
            using (TaskService taskService = new TaskService())
            {
                //using cron
                TaskDefinition taskDefinitionCron = taskService.NewTask();
                taskDefinitionCron.Actions.Add(new ExecAction("c:/foo"));
                var cronMonthly = Trigger.FromCronFormat("? ? * * 3")[0];
                taskDefinitionCron.Triggers.Add(cronMonthly);

                taskService.RootFolder.RegisterTaskDefinition("TestCron", taskDefinitionCron);
            }
```

If you debug this code, you will see that WeeksOfMonth on cronMonthly changes from AllWeeks (befor the add) to FirstWeek | SecondWeek | ThirdWeek | FourthWeek when the Add got executed. 

Extra information: On windows 7 it seems to work. 

Thanks a lot.

**Comment by dahall** [comment]
So the trigger in the cron method is created as
```
new MonthlyDOWTrigger(DaysOfTheWeek.Wednesday, MonthsOfTheYear.AllMonths, WhichWeek.AllWeeks);
```
I have tested and confirmed your bug. It is a change by Microsoft in the handling of the `WhichWeek.LastWeek` enumeration value. It appears that on Windows 10, that value is ignored in lieu of the `RunOnLastWeekOfMonth` property. I have updated the setter property for `WeeksOfMonth` so that if it sees `LastWeek`, it sets `RunOnLastWeekOfMonth` to true. It will appear in release 2.8.3.

**Comment by SebastiaanPolfliet** [comment]
Thank you for your quick response. 

I just tried it out with my test project but without any luck, it still fails... 

I noticed however that if I add a MonthlyDOWTrigger manually (without CRON) it gets registered correctly (both in 2.8.2 and 2.8.3)

This is my test code: 

```
            using (TaskService taskService = new TaskService())
            {
                //cron test
                TaskDefinition taskDefinitionCron = taskService.NewTask();
                taskDefinitionCron.Actions.Add(new ExecAction("c:/foo"));

                taskDefinitionCron.Triggers.AddRange(Trigger.FromCronFormat("0 5 * * 3"));

                taskService.RootFolder.RegisterTaskDefinition("TestCron", taskDefinitionCron);

                //direct Test
                TaskDefinition taskDefinitionDirect = taskService.NewTask();
                taskDefinitionDirect.Actions.Add(new ExecAction("c:/foo"));

                taskDefinitionDirect.Triggers.Add(new MonthlyDOWTrigger(DaysOfTheWeek.Wednesday, MonthsOfTheYear.AllMonths, WhichWeek.AllWeeks));

                taskService.RootFolder.RegisterTaskDefinition("TestDirect", taskDefinitionDirect);
            }
```

And with the following result in Windows TaskScheduler 

![image](https://user-images.githubusercontent.com/6726678/42903208-64b15dd2-8ad1-11e8-9523-e70c786e7268.png)

**Comment by SebastiaanPolfliet** [comment]
Now it works. Thank you very much!
