### ISSUE TITLE
Password required with netstandard/PS Core?

### ISSUE THREAD

**Issue by somewhatlogical** [dahall/TaskScheduler#775]
I am making a quick wrapper around this in PowerShell Core (latest preview, v6.1.0-preview.3), but I seem to have hit an issue.  Not sure if just me / if it effects C# side.  This is using the netstandard .dll and the latest version (2.84, but note this was not working on previous version either for me) on Windows 10 1803.  When I execute RegisterTaskDefinition, I get an error:

> Exception calling "RegisterTaskDefinition" with "7" argument(s): "Could not load the specified file."

`
$ts.RootFolder.RegisterTaskDefinition($Name, $td, [Microsoft.Win32.TaskScheduler.TaskCreation]::CreateOrUpdate, $td.Principal.ToString(), $null, [Microsoft.Win32.TaskScheduler.TaskLogonType]::InteractiveToken, $null)
`

I hit this issue with every TaskLogonType when specifying a UserId in the principal.

I am able to get it registered if I actually do supply the password.  Otherwise, I have tried various other combinations of null principal / empty strings / prefixing user with computer name / tasklogontypes / etc.  Based on what I saw when I tried throwing in a dummy user with a dummy password and receiving the same error, I believe this error is some sort of authentication issue, but I am unsure of what it could be.   I also tried running under administrator / non-administrator under the account I am attempting it on.

Note:  I am able to use the system accounts with the ServiceAccount token without issue, but didn't test groups.  The issue I am hitting is just when specifying a UserId otherwise.  I did look through the C# for this and it does appear that it is going through to the interops, so I don't know if the issue lies internal or how .net standard / PS core are passing it through

**Comment by dahall** [comment]
You are using the following method definition:
```
public Task RegisterTaskDefinition([NotNull] string path, [NotNull] TaskDefinition definition, TaskCreation createType, string userId, string password = null, TaskLogonType logonType = TaskLogonType.S4U, string sddl = null);
```
You seem to have all the parameters. When using InteractiveToken, you must supply the password of the user defined by `userId`. That's a requirement from the native Microsoft library. If you want to skip the password, use `S4U`.

**Comment by somewhatlogical** [comment]
Thanks for the quick response!  I had thought that may be the case, so I had also tried S4U and receive the same error.  Sorry for omitting that!

**Comment by somewhatlogical** [comment]
So, I guess the real issue is that it happens with S4U, not InteractiveToken then

**Comment by somewhatlogical** [comment]
Thanks again for your response.  I got it figured out after loading up a test VM and playing with it there on both core and .NET 4.5.2 only to hit the same issue and was able to narrow it down.  It would appear that PowerShell will implicitly convert the $null to an empty string (which I thought would not happen when calling a .NET method.. thought it would only do it when cast to a certain type.. silly me :O ).  Basically, it will detect it is a string then perform its internal conversion to an empty string on the method call.  Silly PS and its notorious horrible type conversion!

This is the solution:  https://stackoverflow.com/questions/45720150/how-can-i-prevent-a-string-argument-changing-from-null-to-empty-when-bound-to-a

$ts.RootFolder.RegisterTaskDefinition($Name, $td, [Microsoft.Win32.TaskScheduler.TaskCreation]::CreateOrUpdate, $td.Principal.ToString(), [NullString]::Value, [Microsoft.Win32.TaskScheduler.TaskLogonType]::S4U, [NullString]::Value)

I was able to get it going with S4U and InteractiveToken like this (when logged in under the user I am running it as, of course), but not InteractiveTokenOrPassword (probably since there is no password).

Could you maybe add an example of this on the PS wiki?  I feel this information may be useful to other plebians such as myself  :D

**Comment by dahall** [comment]
I have updated the Wiki page. Thanks.
