### ISSUE TITLE
PS Core/NetStandard First-Call issue

### ISSUE THREAD

**Issue by somewhatlogical** [dahall/TaskScheduler#776]
Basically, if I try to run any of the methods that have a default bool parameter, they seem to ignore the bool parameter or maybe throw some different error on the first run.  It happens on TaskFolder.CreateFolder and also on TaskFolder.DeleteFolder from what I have seen (though I would guess it effects all)

The issue does not present itself when using the .NET 4.5.2 .dll of the project and PS 5.1.  This also does not occur in a C# .NET Core Console Project referencing the .NET standard version of the project (ie:  non-module).  However, it does also occur when making a Cmdlet in a binary module (at least targeting .NET standard and running the module in PS Core).  Didn't check PS 5.1 and .NET standard, sorry.  I've omitted the disposals for ease of reading.

So, I am not sure if this is a PS Core / .NetStandard bug or something with a different error being thrown that isn't caught on the first-run.  If you download the latest PS Core (6.1.0 preview 4):  https://github.com/PowerShell/PowerShell

Then run the "ThisWillError/ThisWillNotError/ThisWillError2/ThisWillNotError2" wish pwsh.exe (ps core), from the attached .zip, it should give an idea of what I mean.

[ModuleBugTest.zip](https://github.com/dahall/TaskScheduler/files/2215875/ModuleBugTest.zip)

If you replace the .DLL with the .net 4.5.2 one and run in regular PS, the issue doesn't get hit

**Comment by dahall** [comment]
I think this is a problem with PS. I took the simplest testing route. I fired up the .NET interpretter (cli.exe), loaded the .NET Std 2.0 version of the library (#r dllpath), and then ran the following commands:
```
Microsoft.Win32.TaskScheduler.TaskService.Instance.RootFolder.CreateFolder("Microsoft", null, true);
Microsoft.Win32.TaskScheduler.TaskService.Instance.RootFolder.CreateFolder("Microsoft");
```
Both performed exactly the same.

**Comment by somewhatlogical** [comment]
Cool.  I didn't hit the issue other than when I was playing with PS Core / NET Standard.  I did just run a quick check on something.  In TaskFolder.CreateFolder, I added an extra catch after the COMException catch, then recompiled
```
 catch(Exception ex) {
		        throw new Exception(ex.GetType().AssemblyQualifiedName);
 }
```
Came up with this when running from PS:

"System.IO.FileNotFoundException, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"


---
Curious since the task / folder definitely exists, as would be evidenced by it working after running a second time.  I'm going to tag this over to the PS repo in a bit and see if there is any insight


Slight update:  running without loading from module works as expected:
---
```
$ErrorActionPreference = 'Stop'

# Set the script and directory path, using provided PowerShell variables when available
[string]$_PSScriptPath = $null
[string]$_PSScriptDirectory = $null
if($PSCommandPath -eq $null) { function GetPSCommandPath() { if($MyInvocation.PSCommandPath -eq $null) { return $MyInvocation.MyCommand.Path; } return $MyInvocation.PSCommandPath; } $_PSScriptPath = GetPSCommandPath; if($PSCommandPath -eq $null) { $_PSScriptPath = $MyInvocation.MyCommand.Definition; if($_PSScriptPath -eq $null) { throw New-Object -TypeName 'System.NotImplementedException' 'Unable to identify the path of the current file.'; } } } else { $_PSScriptPath = $PSCommandPath }
if($PSScriptRoot -eq $null) { $_PSScriptDirectory = Split-Path "$_PSScriptPath" -Parent } else { $_PSScriptDirectory = $PSScriptRoot }
if($null -eq $_PSScriptPath -or [string]::IsNullOrWhiteSpace($_PSScriptPath)) { throw New-Object -TypeName 'System.NotImplementedException' 'Unable to identify the path of the current file.'; } if($null -eq $_PSScriptDirectory -or [string]::IsNullOrWhiteSpace($_PSScriptDirectory)) { throw New-Object -TypeName 'System.NotImplementedException' 'Unable to identify the directory of the current file.'; }

[Reflection.Assembly]::LoadFile((Join-Path "$_PSScriptDirectory" 'Microsoft.Win32.TaskScheduler.dll'))
$ts = New-Object 'Microsoft.Win32.TaskScheduler.TaskService'
$tf = $ts.RootFolder
$tf.CreateFolder('\Test', ([NullString]::Value), $false)
$tf.CreateFolder('\Test', ([NullString]::Value), $false)
```
