### ISSUE TITLE
Create Task in Taskscheduler during Installation

### ISSUE THREAD

**Issue by Torchok19081986** [dahall/TaskScheduler#777]
Hallo, i hope some can help me with my problem. 
I tried to create new Task during installation, but if i set Registertaskdefiniton there is always apear username and password to confirm. I also tried to set it from userinput like domain admin user and password, but it stuck after input in create new task for windows. Process stuck and nothing happens, runs endless. Task cant be created, dont know why.

Is there some posibility to set Username and Password in Taskservice Class or somewhere ?
Enviroment:
Test OS Win Server 2016 and 2012 R2 with Hyper-V. 
.NET Framework 4.6.2
Use Visual Studio 2017.

**Comment by dahall** [comment]
I've never seen the process hang unless it is showing a user prompt, so check for that. Each of the TaskLogonType values has different requirements. Read through the help on those to determine which is the right one for your scenario. Many times, if this is a task that runs in the active user's context, the S4U value is sufficient and doesn't require a password.

**Comment by Torchok19081986** [comment]
Many thanks. I going to try all of them. AFAIK to create a schedulertask you need windows rights. I set it to Domain\Administrator with password, but context wasnt S4U. May be that is the problem.
