### ISSUE TITLE
Last Run Time is 1999-11-30 00:00:00 instead of DateTime.MinValue

### ISSUE THREAD

**Issue by stil** [dahall/TaskScheduler#779]
I noticed that property `Task.LastRunTime` returns following 1999 date instead of expected `DateTime.MinValue`

![image](https://user-images.githubusercontent.com/714004/44239489-e357bd80-a1b9-11e8-9967-c43007fb52d9.png)

Windows 10 Pro Version 1709. OS is English, but I use Polish locale.

Using v2.8.4 version of library.

**Comment by dahall** [comment]
When you view this task in the Windows Task Scheduler applet, what does it report for Last Run Time?

**Comment by stil** [comment]
The screenshot in my first post is actually from Windows Task Scheduler applet. The same value is returned by the `Microsoft.Win32.TaskScheduler` API

**Comment by dahall** [comment]
This library uses the native Microsoft library to store and retrieve properties, like `Task.LastRunTime`. Either the native library is recording it that way or it is something on the system that caused its date and time to be incorrectly set the last time the task was run.

**Comment by dahall** [comment]
I can confirm that in my extensive unit and field testing, that property will return DateTime.MinValue if the task has never been run.

**Comment by stil** [comment]
This is what debugger reports:

![image](https://user-images.githubusercontent.com/714004/44270622-5273f700-a238-11e8-9701-932b71173f58.png)

![image](https://user-images.githubusercontent.com/714004/44271018-52282b80-a239-11e8-8040-861f0728bc96.png)

I can see in code that it compares with `v2InvalidDate = new DateTime(1899, 12, 30);` to check if task didn't run.
However if you Google for 11/30/1999 you end up with quite a bit of results related to Task Scheduler.

In my application I'm just going to stick with comparing `LastTaskResult` to SCHED_S_TASK_HAS_NOT_RUN 0x41303 exit code to see if LastRunTime value is going to make sense.

I'm not sure if it's a valid issue, if it's not, please close it

**Comment by hueldoeu** [comment]
i have the same on windows server 2025 LOL

> I noticed that property `Task.LastRunTime` returns following 1999 date instead of expected `DateTime.MinValue`
> 
> ![image](https://user-images.githubusercontent.com/714004/44239489-e357bd80-a1b9-11e8-9967-c43007fb52d9.png)
> 
> Windows 10 Pro Version 1709. OS is English, but I use Polish locale.
> 
> Using v2.8.4 version of library.
