### ISSUE TITLE
enable Task after update

### ISSUE THREAD

**Issue by Torchok19081986** [dahall/TaskScheduler#781]
Hallo , i have questions and hope you can help me with some info.
i have 2 task in taskscheduler and one of them is always active , but second not always. is there some posibilty to recognize task by path to exe ? Name of Task can be diffrently, but path is always same. 
If it posible, how do i reactivate second Task ? Update runs for my product with domain admins rights .

**Comment by dahall** [comment]
I'm not sure what you mean by "active" and "reactivate". Tasks can be enabled and disabled using the `Task.Enabled` property OR task triggers can stop being triggered either by their schedule or by the value of the `EndBoundary` property.

As far as finding a task by the exe path, yes, this is possible but you effectively are enumerating all tasks to do so.
```cs
TaskService.Instance.AllTasks.Where(t => t.Description.Actions.FindIndexOf(a => a.ActionType == TaskActionType.Execute && ((ExecAction)a).Path == myLookupPath) != -1);
```

**Comment by Torchok19081986** [comment]
Many thanks. I mean with active / reactive - enable or disable. I going to try your solution.
