### ISSUE TITLE
Run a scheduled task on remote server

### ISSUE THREAD

**Issue by mcourter** [dahall/TaskScheduler#783]
I'd like to see ASP.NET C# example of how to run a scheduled task on a remote server using the task scheduler.

**Comment by dahall** [comment]
Does this help you in the meantime? https://github.com/dahall/TaskScheduler/issues/534

**Comment by mcourter** [comment]
thanks for the reply.

No, this doesn’t really help.  I’m not having any access denied issues.  I just need to know how to start the scheduled task.  It has a time/date trigger, but the users would like to run it at will from a web page.

we don’t want to use PsExec. 

thanks again.

Michael

**Comment by dahall** [comment]
If you can get an instance of the remote task, then you should be able to run it.
.NET Fiddler link: https://dotnetfiddle.net/1SmLgR
```cs
// No error checking!!
public static void RunRemoteTask(string server, WindowsIdentity user, string taskPath, string[] runParams)
{
   var context = user.Impersonate();
   using (var ts = new TaskService(server))
      ts.GetTask(taskPath)?.Run(runParams);
   context?.Undo();
}
```
You may need the `RunEx` command that let's you specify conditions and a user when in that remote context.

**Comment by mcourter** [comment]
thanks much!

will try tomorrow morning.

**Comment by mcourter** [comment]
I see why you referred to the link in your previous email.  Need the Impersonate() method.

**Comment by dahall** [comment]
Can I assume you got it to work?

**Comment by mcourter** [comment]
sorry, not yet.

several JIRA tickets popped in front of the queue this morning…heh

will let you know.

thanks for follow up.

**Comment by mcourter** [comment]
well I don’t think I’m going to be able to use C# 6 without a fuss around here…

**Comment by mcourter** [comment]
not sure of the syntax?  I get a "Object reference not set to an instance of an object." error.

using (TaskService ts = new TaskService(@"\\<myServer>”, "myUser", "myDomain", "myPassword"))
{
   try
   {
      ts.GetTask("C:\\Windows\\System32\\schtasks.exe").Run("/S <server> /U <myUser> /P <myPassword> /run /TN myTaskName");

**Comment by dahall** [comment]
Why do you need C# 6? There is nothing in the sample code that cannot be translated to C# 2. Calling the function I posted would look like:
```cs
RunRemoteTask("MYSERVER", new WindowsIdentity("john@mydomain.com"), "MyCom\\MyTask", null);
```

**Comment by mcourter** [comment]
I just realized I don’t.  just removed the null checker ‘?’ 

I sent another email.  I’m not sure what to feed the gettask call.

no luck with:

ts.GetTask("C:\\Windows\\System32\\schtasks.exe").Run(ts.RootFolder.Tasks["vatsMonthlyStatements - Marquette"].ToString());

**Comment by dahall** [comment]
The name of the task path inside the Task Scheduler. See my example. If it is in a folder, then specify the folder hierarchy separated with '\' with no backslash on the front. Then the name of the task. For example, a task you may have in the root folder would be "BitLocker Reminder". A task you might see in a folder would be @"Microsoft\Windows\Bluetooth\UninstallDeviceTask".

Also, the parameters after the first in the TaskService constructor should be null. The parameters to the Run method is a string array (e.g. `new string[] { "value1", "value2" }`) or null. Most of the time it is null. Please refer to my sample code (first and later posts).

**Comment by dahall** [comment]
Full code with example and error checking: https://dotnetfiddle.net/YNTQva

**Comment by mcourter** [comment]
System.TypeInitializationException

  HResult=0x80131534

  Message=The type initializer for 'Microsoft.Win32.TaskScheduler.TaskService' threw an exception.

  Source=Microsoft.Win32.TaskScheduler

  StackTrace:

   at Microsoft.Win32.TaskScheduler.TaskService.GetLibraryVersionFromLocalOS()

   at Microsoft.Win32.TaskScheduler.TaskService.ResetHighestSupportedVersion()

   at Microsoft.Win32.TaskScheduler.TaskService.ResetUnsetProperties()

   at Microsoft.Win32.TaskScheduler.TaskService.Connect()

   at Microsoft.Win32.TaskScheduler.TaskService.set_TargetServer(String value)

   at Microsoft.Win32.TaskScheduler.TaskService..ctor(String targetServer, String userName, String accountDomain, String password, Boolean forceV1)

   at main_printletters.RunRemoteTask(String server, WindowsIdentity user, String taskPath, String[] runParams) in c:\Users\mcourter.RPS\Source\repos\vatsDashboardWebForms\main\printletters.aspx.cs:line 410

   at main_printletters.btnGenerateMonthlyStatements_Click(Object sender, EventArgs e) in c:\Users\mcourter.RPS\Source\repos\vatsDashboardWebForms\main\printletters.aspx.cs:line 162

 

Inner Exception 1:

NotSupportedException: The Task Scheduler library version for this system cannot be determined.

**Comment by mcourter** [comment]
The error message I sent to you is new.  I tried again with my old code which was at least able to create the task service and it is getting this new error.

**Comment by mcourter** [comment]
I have it working in a console app using a server on our network.

now I am trying to make it work with an Azure server.  

I receive this error



System.Runtime.InteropServices.COMException

  HResult=0x80070032

  Message=The request is not supported. (Exception from HRESULT: 0x80070032)

  Source=<Cannot evaluate the exception source>

  StackTrace:

<Cannot evaluate the exception stack trace>

does the interop service need something different for Azure?

**Comment by mcourter** [comment]
looks like there is no interop service in Azure.

**Comment by dahall** [comment]
If Azure is running a full version of Windows, then it should be there. If only a partial or if this is just a service, then it will not. I'm looking into that method that threw the TypeInitializationException exception. I think there is a minor bug there. I should have more data shortly.

**Comment by dahall** [comment]
I found a bug that may (or may not) be related to the error you're seeing. I have fixed it in release 2.5.8 which is now available. Please update your NuGet package and let me know if the exception persists.

**Comment by mcourter** [comment]
with new NuGet

UnauthorizedAccessException: Retrieving the COM class factory for component with CLSID {0F87369F-A4E5-4CFC-BD3E-73E6154572DD} failed due to the following error: 80070005 Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)).

**Comment by dahall** [comment]
Access denied can happen a two places during the connection:
1. When trying to access the COM server.
2. When trying to connect to the remote task service.

Both topics are covered in the Wiki: https://github.com/dahall/TaskScheduler/wiki/TaskSecurity

**Comment by mcourter** [comment]
I wasn’t getting that error before.  I was able to create the task scheduler object, but didn’t know how to run it.  Now I cant create the object using the same code that was working.

**Comment by dahall** [comment]
Please reopen if you want me to continue to investigate.
