### ISSUE TITLE
Works via RPC, could it also be expanded to use WinRM?

### ISSUE THREAD

**Issue by EskeRahn** [dahall/TaskScheduler#785]
It is GREAT that by your package be able to get to info beyond the old _Win32_ScheduledJob_

I'm interested in examining what is running on a number of machines, and this works fine if the machines are open for RPC (or if executed on the machine).

But would it be possible to make it use Cim and WinRM also/instead?
As it seems much more common that **WinRM** is open on machines than **RPC**.

Similar to this partial code for services
```
using Microsoft.Management.Infrastructure
.
.
System.Security.SecureString securepassword = new System.Security.SecureString();
foreach (char c in password) securepassword.AppendChar(c);
WSManSessionOptions SessionOptions = new WSManSessionOptions();
if (username!=null && username!="") { 
    CimCredential Credentials = new CimCredential(PasswordAuthenticationMechanism.Default
                                                  , domName, username, securepassword);
    SessionOptions.AddDestinationCredentials(Credentials);
}
CimSession Session = CimSession.Create(host, SessionOptions);
var allServices = Session.QueryInstances(@"root\cimv2", "WQL", "SELECT * FROM Win32_Service");
foreach (var itm in allServices) {
    var sName = itm.CimInstanceProperties["Name"].Value;

```
over the variant using RPC
```
using System.Management;
.
.
ConnectionOptions options = new ConnectionOptions();
if (username != null && username != "") {
    options.Username = username;
    options.Password = password;
}
ManagementScope scope = new ManagementScope($"\\\\{host}\\root\cimv2", options);
scope.Connect();
ManagementObjectSearcher searcher = new ManagementObjectSearcher(scope
                                              , new ObjectQuery("select * from Win32_Service"));
var allServices = searcher.Get();
foreach (var itm in allServices) {
    var sName = itm.GetPropertyValue("Name");

```

**Comment by dahall** [comment]
I don't think I'm clear on your request. This library is simply a wrapper around the native Microsoft API for Task Scheduler. All remote connections are done through that API. Unless Microsoft decides to open up their API for WinRM/Cim, I am unable to do anything different.

**Comment by dahall** [comment]
The Win32_ScheduledJob uses an API developed many years ago that only supports AT jobs which were deprecated starting with Windows 8. The Task Scheduler API (which this library wraps) is the currently supported model. I know of no means in WMI to get scheduled tasks.

**Comment by EskeRahn** [comment]
Thanks for your reply.
Even though an awkward way of doing it, it IS possible through schtasks.exe with a /v to get the info through WinRM. It can give an CSV formatted output that then can be interpretted. So that is why I had hoped there were a nice way of doing it too.. :)

**Comment by dahall** [comment]
There are two versions of the Task Scheduler library from Microsoft, version 1 and version 2. This wrapper library can support both. The /V1 switch on schtasks.exe effectively does the same thing as creating a TaskService instance with the `forceV1` parameter set to `true`.

**Comment by EskeRahn** [comment]
Ah, well but I'm talking /V not /V1. See
`schtasks /query /?`
I execute it in this form
`schtasks.exe /query /s pcname /U username /P password /V /FO CSV`
(And this goes through WinRM, and thus must use a different API, or some special switch)

Note that it stupidly tries to prohibit you from using credentials to the local machine.
(For odd workaround see https://eskerahn.dk/wordpress/?p=2724 but that is another story) 

...Also note that their CSV output is not clean, and needs filtering, as the header record is inserted multiple times, but again a different story.

**Comment by dahall** [comment]
The /V just makes it verbose, it does not change its authentication mechanism. How have you determined it is using WinRM?

**Comment by EskeRahn** [comment]
Well I'm not _100%_ sure it is WinRM, it could in theory be a third protocol, but I'm sure it is not RPC, as it works pointing to machines where RPC does not work, and works for all machines I have addressed where WinRM works. And it have failed towards machines where WinRM fails.

(And yes, I just mentioned the /V to tell that we can get more than the most basic info out of the program)
