### ISSUE TITLE
Error creating task on Windows 2008

### ISSUE THREAD

**Issue by WouterTinus** [dahall/TaskScheduler#786]
One of our Windows 2008 users is reporting issues creating a task that runs as SYSTEM on Windows 2008. I was able to reproduce this on one of my own servers.

`System.ArgumentException: A valid system account name must be supplied for TaskL
ogonType.ServiceAccount. Valid entries are "NT AUTHORITY\SYSTEM", "SYSTEM", "NT
AUTHORITY\LOCALSERVICE", or "NT AUTHORITY\NETWORKSERVICE".
Parameter name: userId`

My code is 
```cs
_log.Debug("Creating task to run as system user"); 
task.Principal.UserId = "SYSTEM"; 
task.Principal.LogonType = TaskLogonType.ServiceAccount; 
taskService.RootFolder.RegisterTaskDefinition(taskName, task, TaskCreation.CreateOrUpdate, null, null, TaskLogonType.ServiceAccount);
```

The same code used to work fine with version 2.6.5, so it might be a bug in the 2.8.x series?

See https://github.com/PKISharp/win-acme/issues/884

**Comment by dahall** [comment]
I just ran your code using v2.8.6 and could not reproduce the error. I ran the following. Are you doing something different? Is this not a new task?
```cs
var task = ts.NewTask();
task.Actions.Add("notepad", null, null);
task.Principal.UserId = "SYSTEM";
task.Principal.LogonType = TaskLogonType.ServiceAccount;
ts.RootFolder.RegisterTaskDefinition("Test", task, TaskCreation.CreateOrUpdate, null, null, TaskLogonType.ServiceAccount, null);
```

**Comment by dahall** [comment]
Has your issue been resolved? If I don't hear back from you soon, I will close this issue.

**Comment by WouterTinus** [comment]
Hi @dahall, sorry for the late reply. The issue has not been resolved AFAIKT. 

Here is the relevant source file: https://github.com/PKISharp/win-acme/blob/master/letsencrypt-win-simple/Services/TaskSchedulerService.cs

There are some possibly relevant properties different from your test case, e.g. `task.Principal.RunLevel = TaskRunLevel.Highest;` but you also raise a good question:

> Is this not a new task?

The program offers user to recreate the existing task, for when they feel that it's settings have to be reset. In that case we try to recreate it with the same logon options that were previously used, e.g. we read them from an existing task and re-apply them to the new TaskDefinition.

So to modify your example

       var task = ts.NewTask();
       task.Actions.Add("notepad", null, null);
       task.Principal.UserId = "SYSTEM";
       task.Principal.RunLevel = TaskRunLevel.Highest; 
       task.Principal.LogonType = TaskLogonType.ServiceAccount;
       ts.RootFolder.RegisterTaskDefinition("Test", task, TaskCreation.CreateOrUpdate, null, null, TaskLogonType.ServiceAccount, null);     
  
      var existingTask = ts.GetTask('Test');
      var refreshTask = ts.NewTask();      
      refreshTask.Actions.Add("notepad", null, null);
      refreshTask.Principal.RunLevel = TaskRunLevel.Highest; 
      refreshTask.Principal.UserId = existingTask.Definition.Principal.UserId;
      refreshTask.Principal.LogonType = existingTask.Definition.Principal.LogonType;
      ts.RootFolder.RegisterTaskDefinition("Test", refreshTask, TaskCreation.CreateOrUpdate, null, null, existingTask.Definition.Principal.LogonType, null);       

I don't have easy access to a Windows 2008 machine, so I hope you can test this!

**Comment by dahall** [comment]
I just ran the above code on WS2008R2 without error (except I had to double quote the task name in GetTask).

**Comment by WouterTinus** [comment]
Hi @dahall, thanks for trying that. There must be some other problem then. We'll try to figure it out on our end and get back to you here if we have a reproducible case!
