### ISSUE TITLE
Create Task From date to date

### ISSUE THREAD

**Issue by angelfoga** [dahall/TaskScheduler#787]
Hi, sorry if this is an obvious question.
Is it possible to create a recurrent task from an especific datetime or do I have to get the difference and use it in the days interval when creating daily triggers?
Like 
`datetime1 - datetime2 = datetimediff;`
`var dt = td.Triggers.Add(new DailyTrigger(datetimediff));`
Thanks!

**Comment by dahall** [comment]
The `StartBoundary` property of all `Trigger` derived classes is the time at which the trigger become _active_. For example, if you need a trigger to run every second day starting tomorrow, you could code:
```cs
DateTime tomorrow = DateTime.Today + TimeSpan.FromDays(1);
var every2ndDayTrigger = new DailyTrigger(2) { StartBoundary = tomorrow };
td.Triggers.Add(every2ndDayTrigger);
```
