### ISSUE TITLE
Trigger for first or last business day of month

### ISSUE THREAD

**Issue by jdschuitemaker** [dahall/TaskScheduler#791]
I would like to be able to set a monthly trigger for the first business day or last business day of a month. So, not a trigger that runs on any Saturday or Sunday. I played with monthly triggers for first day of month, but they do run sometimes in the weekend.

I dont' think this is possible with current functionality, correct?

**Comment by dahall** [comment]
I can't think of a way to do that other than calculate it externally and then create a specific TimeTrigger for each month.

**Comment by jdschuitemaker** [comment]
Thank you for your prompt reply! 

For now I work around this by running on the first or last day of the month and set the option "run task as soon as possible after a scheduled start is missed" (TaskDefinition.Settings.StartWhenAvailable = True).
