### ISSUE TITLE
Cannot update package dependencies

### ISSUE THREAD

**Issue by InteXX** [dahall/TaskScheduler#793]
**Describe the bug**
Cannot update package dependencies.

**To Reproduce**
1. Install the `TaskSchedulerEditor` package
2. Note that the package's dependent packages cannot themselves be updated:
a. AeroWizard
b. GroupControls
c. TimeSpan2
d. Tulpep.ActiveDirectoryObjectPicker

**Expected behavior**
The aforementioned packages should be able to be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/10966749/50427878-011aea80-085e-11e9-8c88-3a8d1012746c.png)
![image](https://user-images.githubusercontent.com/10966749/50427884-09732580-085e-11e9-8cbd-f694cbfc0f61.png)

**Environment (please complete the following information):**
 - Host Windows version (the one running the code): **Win10 Pro v1809**
 - Library version: **TaskSchedulerEditor v2.8.6**
 - Remote Windows version (if applicable): **N/A**

**Additional context**
This is occuring because the `TaskSchedulerEditor` package is requiring fixed versions for its dependencies (e.g. `AeroWizard (= 2.1.11)` instead of `AeroWizard (>= 2.1.11)`).

**Comment by dahall** [comment]
Nice catch. I can't believe it took this long for someone to find something so basic. I will get this resolved in the next release. Thank you.

**Comment by InteXX** [comment]
Keep up the good work  :-)

**Comment by dahall** [comment]
In testing, I have found a problem with implementing the ">= x.x.x" option. In 2.8.x and earlier, this library supports .NET 2.0, 3.5, 4.0 and 4.5.**2**. The new versions of the dependencies support .NET 2.0, 3.5, 4.0 and 4.5.**0**, thus breaking any project building a project newer than 4.5. The next version of the library (3.0) also will build against 4.5.0 as to alleviate this problem. Unfortunately, that version also has a lot of other changes that are not ready for release and won't be for a while. The good news is that the change from 4.5.2 to 4.5.0 is the only functional change to the dependent libraries so upgrading them really gains you nothing.

**Comment by InteXX** [comment]
Very good, thanks for the update.

**Comment by ixm7** [comment]
What is the recommended way around this issue in order to update to latest version?

**Comment by dahall** [comment]
The library is tested with the versions included. There is no "workaround" to update the other packages. When I release the next version, I'll update the package dependencies.

**Comment by delfuria** [comment]
Hi, do you have any news about this "dependency" issue ?
I still cannot update the package.
Thanks in advance

**Comment by dahall** [comment]
I have corrected this and will shortly push 2.8.10 with the updated dependencies.
