### ISSUE TITLE
run with highest privileges windows 10 

### ISSUE THREAD

**Issue by mostafa-zaghloul** [dahall/TaskScheduler#794]
i tried to create a task to run on logon and with highest privileges but without running my app as administrator under windows 10 ( (UAC) is turned on and my logon account type is local account and an Administrator with no password  ) .. it works well if added manually in task scheduler but in code it gives me  : System.UnauthorizedAccessException: 'Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))' when registering the task to the rootfolder.
and here is my code :  

`
using (TaskService ts = new TaskService())

                {

                    TaskDefinition td = ts.NewTask();

                    td.Settings.Hidden = true;

                    td.Principal.RunLevel = TaskRunLevel.Highest;

                    td.RegistrationInfo.Description = "Does something";

                    td.Triggers.Add(new LogonTrigger { UserId = System.Security.Principal.WindowsIdentity.GetCurrent().Name, Enabled = true });
                    td.Actions.Add(new ExecAction("C:\\Users\\ATOM\\source\\repos\\UpdateProcess\\UpdateProcess\\bin\\Debug\\UpdateProcess.exe", "c:\\test.log", null));

                    ts. RootFolder.RegisterTaskDefinition("TaskName", td, TaskCreation.CreateOrUpdate, System.Security.Principal.WindowsIdentity.GetCurrent().Name, null, TaskLogonType.S4U);
	            }
`

**Comment by dahall** [comment]
Exactly as I expect. The Task Scheduler app in Windows forces account privilege elevation via its manifest and bypasses UAC. For your code to work, your application needs to do the same.

**Comment by mostafa-zaghloul** [comment]
aha so no way to run this without changing the default manifest to high privilege which'll make the app run as administrator using the AUC .
thanks

**Comment by dahall** [comment]
Correct
