### ISSUE TITLE
Failed to add reference. "...possibly a bug in the package. Please contact package owners..."

### ISSUE THREAD

**Issue by RevealedFrom** [dahall/TaskScheduler#797]
**Describe the bug**
Using NuGet to add it a Visual Studio project and met with:

>Failed to add reference. The package 'Microsoft.Win32.TaskScheduler' tried to add a framework reference to 'Microsoft.Win32.TaskScheduler, Version=2.2.0.18504, Culture=neutral, PublicKeyToken=0d013ddd5178a2ae' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**To Reproduce**
1. In Visual Studio, run Manage NuGet Packages...
2. Search for Microsoft.Win32.TaskScheduler
3. Select Install Latest stable 2.2.0.3

**Environment (please complete the following information):**
 - Host Windows 10 Pro 10.0.17763 Build 17763
 - Library version:

**Comment by dahall** [comment]
That's not my package. To get the package associated with this project, select `TaskScheduler` by David Hall. Version 2.8.7 is the latest.
