### ISSUE TITLE
Some tasks cannot be found

### ISSUE THREAD

**Issue by RevealedFrom** [dahall/TaskScheduler#798]
Is there a criteria for when a task might not be returned from `TaskService.GetTask`?

My `RootFolder` has 12 tasks as follows:

![image](https://user-images.githubusercontent.com/5305957/52386285-56365700-2ac0-11e9-8e7e-e020cd8b33a7.png)

However, enumerating `RootFolder` gives me only 9. The three missing are the two GoogleUpdate ones and Test. What properties of these tasks could have caused them not to be found?

**Comment by dahall** [comment]
Interesting that those 3 are V1 tasks (XP version). What happens if you append ".job" to the name of the task? Does it find them then?

**Comment by RevealedFrom** [comment]
Thanks for getting back. I tried `GetTask("Test.job")` it also returned null.

How do you tell they are V1? I created `Test` using the UI **Create task...** and this is a Windows 10 Pro machine. Is there a way to set the version?

**Comment by dahall** [comment]
If your code is also not running elevated, then the number of tasks you can see could also be limited to just those for which you have full access rights.

**Comment by dahall** [comment]
I guess the first question I should ask is which UI? Microsoft's or the library's? To create a task as V1 you have to create TaskService using the forceV1 flag and then create your task normally. If you are not targeting systems before Vista, then it is completely unnecessary. To tell the difference, you look at the "Configure for.." on the General tab. If it says XP, then you know it is a V1 task.

**Comment by RevealedFrom** [comment]
By UI I meant the Microsoft's TASKSCH.exe.

Other than that task named `Test`, it is working fine for all other tasks I have created (via Microsoft's UI).  I can't identify any differences between `Test` was and the other tasks I created. I guess I will just ignore it for the moment until more clues surface in future.

**Comment by dahall** [comment]
Is the application running elevated "As Administrator"? If not, try that and see if the task is then visible.

**Comment by RevealedFrom** [comment]
Yes, that solved the problem. Thanks!
