### ISSUE TITLE
Configure for combo blank on focus

### ISSUE THREAD

**Issue by alexdyb** [dahall/TaskScheduler#8]
Hi,
when i have XP Visual styles turned off and open TaskEditDialog "Configure for" combo appears to be blank on get focus, see below:
![image](https://user-images.githubusercontent.com/32156905/31167514-02de38b8-a8fb-11e7-8f9b-f374a25ce769.png)

**Comment by dahall** [comment]
Thanks for the picture and OS detail. I'll look at it this week for inclusion in the 2.6.2 release.

**Comment by alexdyb** [comment]
Thanks! Same on Windows Server 2012.
BTW,  is it possible to have dialog with "XP Visual styles" turned on when I run dll from command prompt project or other DLL project?

**Comment by dahall** [comment]
Fixed (2.6.2)
