### ISSUE TITLE
Delete All Tasks under subfolder

### ISSUE THREAD

**Issue by bassemwadie** [dahall/TaskScheduler#800]
Hello , 

I know how to delete a task under folder but is there a method that enables me to delete all tasks under sub folder  ( without foreach )
when i try to delete a folder , exception fire because it contains tasks

Thanks

**Comment by dahall** [comment]
There is no method in the library to do that. You'd have to approach it like any recursive tree deletion using foreach+DeleteTask and DeleteFolder for children and descendants.
