### ISSUE TITLE
Question: How to show Time to execute for next Task in TaskScheduler

### ISSUE THREAD

**Issue by Torchok19081986** [dahall/TaskScheduler#801]
Hallo, i have a question and hope someone can help me with. I can add new Task in TaskScheduler. Works good. I want to know, if there some possibility to show time to next myTask which are being executed in reverse. Example Tasktime was set to 23:00 and i open my mainform at 16:00 to show remain time to taskrun, which are 7 hours.

**Comment by dahall** [comment]
```cs
myTask = // Some task you've created or opened
var nrt = myTask.NextRunTime;
var durToNextRun = nrt - DateTime.Now;
```
