### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by InteXX** [dahall/TaskScheduler#803]
**Describe the bug**
Referenced documentation appears to be missing.

**To Reproduce**
1. Go to https://github.com/dahall/taskscheduler#sample-code
2. Note this paragraph: _"There is a help file included with the download that provides an overview of the various classes. There are numerous examples under the 'Documentation' tab."_
3. Clone the repository
4. Note that the referenced help file isn't found in the cloned repository
5. Note that there _is_ a file `index.html` in the `docs` subfolder, but that help collection doesn't include a Documentation tab as described.

**Expected behavior**
I expected to find the referenced help file.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by dahall** [comment]
Download: https://github.com/dahall/TaskScheduler/releases
Online: https://dahall.github.io/TaskScheduler/html/R_Project_TaskScheduler.htm

**Comment by InteXX** [comment]
@dahall Got it, thank you.
