### ISSUE TITLE
Error building documentation

### ISSUE THREAD

**Issue by InteXX** [dahall/TaskScheduler#804]
**Describe the bug**
The Help builder cannot find the documentation to build.

**To Reproduce**
1. Extract the contents of the [.ZIP file](https://github.com/dahall/TaskScheduler/releases/download/v2.8.8/TaskSchedulerHelp.zip) to disk
2. Open a command prompt
3. Navigate to the folder where you extracted the files
4. Run the command `Install_TaskScheduler.bat 2.3` (Where the version specified is one of the versions found in `%ProgramFiles(x86)%\Microsoft Help Viewer`)
5. Note the error message that results: `The specified content does not exist or is unreadable.`
6. Click OK in the `MessageBox`
7. Cancel the action by selecting No at the UAC prompt

**Expected behavior**
I expected the builder to prepare and install the Help documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/10966749/54886617-cfa2c280-4e3e-11e9-9bf9-f18311498f89.png)

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by dahall** [comment]
Are you able to import the `TaskScheduler.msha` directly into the Help Viewer?

**Comment by InteXX** [comment]
Yes, that worked. I'm satisfied. (Although I would like to change "Vendor Name" to something more meaningful, if possible.)

On another note, I'm very interested in doing this as well to document my own internal frameworks. I'm weary of digging through the source to find out what method call I should use for a given task, and what class/namespace it's in.

Do you have any links/references to guidance on the process?

**--EDIT--**

I was able to change "Vendor Name" like so:

1. Uninstall the Help content
2. Edit the XML in `TaskScheduler.msha` to reflect the desired name
3. Reinstall the Help content (the first version seems to be cached, so I installed from a new location)

I also was able to change the title of the topic node in the Help Viewer TreeView:

1. Uninstall the Help content
2. Rename `TaskScheduler.mshc` to `TaskScheduler.mshc.zip`
3. Open the renamed file with WinZip
4. Locate and select the file `html\R_Project_TaskScheduler.htm`
5. Press Shift+V and open the file in Notepad
6. Edit the `<Title />` and corresponding `<meta name="Title" />` elements
7. Save the changes and close Notepad
8. WinZip will prompt to update the .ZIP file with the changes
9. Save the modified .ZIP file (on the File menu)
10. Rename `TaskScheduler.mshc.zip` to `TaskScheduler.mshc`
11. Reinstall the Help content

**Comment by InteXX** [comment]
I continue to be impressed with the quality of your workmanship.

**Comment by dahall** [comment]
Thanks for the notes on the title and vendor name. I have updated their sources so they'll provide more descriptive text in the next build and release.

I'm not sure why the batch file isn't working. It has been some time since anyone even asked for the MS Help version. Most people use the online version. The help file is almost completely derived from the XML comments in the code files. I then use Sandcastle Help File Builder (SHFB) to compile it all. It is relatively easy to use. You can find good instructions on their GitHub page.

**Comment by InteXX** [comment]
> I have updated their sources so they'll provide more descriptive text in the next build and release.

Very good, thank you.

> I'm not sure why the batch file isn't working.

The batch file works perfectly. I think it's a problem somewhere inside `HelpLibraryManagerLauncher`. Someday I might inquire over there, but for now this works just fine.

> It has been some time since anyone even asked for the MS Help version. Most people use the online version.

Really! I find that odd. The deep integration with the IDE is invaluable. It's so very nice to be able to click anywhere in the word `TaskService`, press F1 and get an immediate listing of all properties, methods, events, etc.

I'm still looking for those samples you're talking about, but I'm sure they're in there somewhere  ;-)

> You can find good instructions on their GitHub page.

Sounds good, I'll have a look.

**Comment by dahall** [comment]
https://github.com/EWSoftware/SHFB

**Comment by InteXX** [comment]
Got it, thanks.

**Comment by InteXX** [comment]
re: those samples—I just found them.

Any member that displays a Code Example image:

![image](https://user-images.githubusercontent.com/10966749/54959630-99cd0f00-4f0e-11e9-9b2b-e48dc3fcb667.png)

...contains a sample.
