### ISSUE TITLE
TaskEventLog class seem to have some default filtering operations?

### ISSUE THREAD

**Issue by youxiaotian** [dahall/TaskScheduler#806]
I use TaskEventLog class to get a log of a scheduled task, but the number of views viewed from windows and seen from the code seems inconsistent, is there a default filtering of certain types of data? （There seems to be some warning logs that will be ignored, but I didn't find a description of this part in the document, did I not see it carefully enough?）

In windows ：
![image](https://user-images.githubusercontent.com/35222088/56404065-2e6d2780-6297-11e9-9143-8503e17eaa85.png)

In code：
![image](https://user-images.githubusercontent.com/35222088/56404094-59f01200-6297-11e9-8a3f-dcd0f20ae164.png)

**Comment by dahall** [comment]
Were you able to find the answer on your own? For curiosity, what caused what you were seeing?
