### ISSUE TITLE
E_ACCESSDENIED ISSUE

### ISSUE THREAD

**Issue by slohman** [dahall/TaskScheduler#807]
**Describe the bug**
E_ACCESSDENIED when creating a remote task

**Environment (please complete the following information):**
 - Host Windows version (the one running the code): Win10 
 - Library version:2.8.11
 - Remote Windows version (if applicable):WIN 10

**Additional context**
I can create a task on the local machine without issue as long as the app is run as an "Administrator" even thought the logged in "Domain User" is a local admin. When I try to starta remote task service like , TaskService ts = new TaskService("DMETERCTL","scott","DemeterCtrl","xxxxxxxxx",false);

I get an instant E_ACCESSDENIED. Ran the trouble shooter with no issues yet I always get the E_ACCESSDENIED. Firewalls are set correctly. Even thought I'm logged in to a non domain account user, which is an administrator the following:

                var identity = WindowsIdentity.GetCurrent();
                var principal = new WindowsPrincipal(identity);
                
                if (principal.IsInRole(WindowsBuiltInRole.Administrator))

isInRole does not = WindowsBuiltInRole.Administrator even though user is. 

Pretty sure you've seen this error a few times:

Message = "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"

I can get away with local implementation but having the remote ability would be far better.

Thanks

Scott

**Comment by dahall** [comment]
I only have a couple ideas for things that cause this beyond what the troubleshooter can do:
1) The account you're using may not have the privilege needed on the remote machine. Please read the following links carefully and make sure all the conditions are met:
 * https://github.com/dahall/TaskScheduler/wiki/TaskSecurity
 * https://docs.microsoft.com/en-us/windows/desktop/taskschd/security-contexts-for-running-tasks
 * https://docs.microsoft.com/en-us/windows/desktop/taskschd/task-security-hardening
2) If you are using a firewall other than Microsoft's (McAfee, Norton, etc.), you will need to ensure the exceptions noted in the links above also have been added to those firewalls.

**Comment by slohman** [comment]
I’ll keep digging. It’s definitely a user access issue. Can’t even connect remotely from the task manager on my desktop to the machine in question using the administrator creds on the remote machine. Something else is in play
