### ISSUE TITLE
Catch response when creating a scheduled task based on XML and AD Account

### ISSUE THREAD

**Issue by FrederikZutterman** [dahall/TaskScheduler#808]
**Describe the bug**
String Xml = File.ReadAllText(XmlFile);
Microsoft.Win32.TaskScheduler.Task t = TaskService.Instance.RootFolder.RegisterTask(Task.TaskName, XmlFile, TaskCreation.Create, Globals.SaUn, Globals.SaPw, TaskLogonType.Password);

When running this code I get an exception that has nearly any information. The only response I get on my screen is : 
(1,2)::
and absolutely nothing else.

**Expected behavior**
I would like some reponse so I know what is wrong and want I have to adjust in my code

**Screenshots**

**Environment (please complete the following information):**
 - Host Windows version (the one running the code): Windows Server 2008 R2 Standard
 - Library version: .NET 4.7.2
 - Remote Windows version (if applicable):

**Additional context**

**Comment by dahall** [comment]
Yep, I hate those errors too. They come from the underlying Microsoft COM library when `ITaskFolder::RegisterTaskDefinition` can't process the XML syntax or the XML produced by building a task using properties. Effectively, it says it couldn't process the XML at (row,col), which in your case was (1,2). My best guess is that the header is wrong in the XML file. Export a working task using the Task Scheduler OS tool and see it's header for an example.

**Comment by FrederikZutterman** [comment]
David,

First of all thank you for your superfast reply. At least now I know where to search.

The weird thing however is that that xml file variable is a actually a scheduled task I created via the schedueled task manager and exported as a template.

What my code does is the following :
- Depending on the task, it selects one out of 2 templates and reads this into a XmlDocument variable
- I change some of the node values
- I save this xml to a new location and return the full path of this new xml to the create funtion

so bottom line the first line of the xml stays unchanged and is everywhere the same :
`<?xml version="1.0" encoding="UTF-16"?>`

I compared this to a working scheduled task and this is identical.
The only thing I can  imagine that is going on is that with reading the content of this file with File.ReadAllText(), that .net is adding unvisible chars at the beginning of the variable.
When I print this string it shows up perfectly on my screen.

I just compared a file from the task folder with my created xml task template with a hex editor to see if there are any diffrences. They seem to be identical in the hex editor as well. I'm a bit clueless for the moment.

I changed my line from
String Xml = File.ReadAllText(XmlFile);
to
String Xml = File.ReadAllText(XmlFile, System.Text.Encoding.Unicode);

This unfortunately results in exactely the same message.

I also tried to go to Task Scheduler and import a task based on this newly created xml template file.
This works perfectly without a hitch. So the windows Task Scheduler has no issue reading this same xml file.

Any other recommandations on your part?

thank you.

**Comment by dahall** [comment]
I'll play with file encodings today and report my findings. This has not been a problem in the past decade, so I'm not sure what I'll find.

**Comment by dahall** [comment]
Just for kicks, try the following:
```cs
var td = NewTask();
td.XmlText = System.IO.File.ReadAllText(xmlFile);
Microsoft.Win32.TaskScheduler.Task t = TaskService.Instance.RootFolder.RegisterTaskDefinition(Task.TaskName, td, TaskCreation.Create, Globals.SaUn, Globals.SaPw, TaskLogonType.Password);
```

**Comment by FrederikZutterman** [comment]
I did a workaround, for future improvements I will for sure try this.

Thank you for the information David and kudos on the lib !

**Comment by dahall** [comment]
If you wouldn't mind, please share your work-around.

**Comment by FrederikZutterman** [comment]
Sure, I just used the schtasks command in a Process:

```
String arguments = string.Format("/CREATE /S {0} /TN \"{1}\" /XML \"{2}\" /RU {3} /RP {4}", TargetComputer, Task.TaskName, XmlFile, Globals.SaUn, Globals.SaPw);
                Process proc = new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        FileName = "schtasks.exe",
                        Arguments = arguments,
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        CreateNoWindow = false
                    }
                };

                proc.Start();
                proc.WaitForExit();
```

After that I have an other function that checks if the task exists and gives feedback upon the return
