### ISSUE TITLE
Task to be run whenever a user (any user) logs on

### ISSUE THREAD

**Issue by vlad-nica** [dahall/TaskScheduler#809]
Hi,

What I'm trying to achieve is creating a task that would run whenever a user (any user) is logging in.
So basically if the system has 2 users, the task should trigger in the following scenarios:
- system boots up and user signs in -> task triggers after login
- a user (user1) switches to another account (user2) -> should trigger twice, once for each user
- logs out and logs in back -> should trigger

I came up with the following code but my feeling is that I'm doing it wrong, given the magic string specifying the "Users" group as userId parameter.

```
using (TaskService ts = new TaskService())
            {
                TaskDefinition td = ts.NewTask();
                
                td.Principal.RunLevel = TaskRunLevel.Highest;
                td.RegistrationInfo.Description = "Start whenever a user logs in";                
                td.Triggers.Add(new LogonTrigger());
                td.Actions.Add(new ExecAction("PATH_TO_EXE", "SOME_PARAM", null));
                td.Settings.DisallowStartIfOnBatteries = false;
                td.Settings.DisallowStartOnRemoteAppSession = false;
                td.Settings.Hidden = true;
                td.Settings.StopIfGoingOnBatteries = false;

                ts.RootFolder.RegisterTaskDefinition(
                      "task-to-run-on-logon",
                      td, 
                      TaskCreation.CreateOrUpdate,
                      "Users", // grrrrrr...
                      logonType: TaskLogonType.Group
               );
            }
```

Is this gonna work on other systems that are in different languages or where the default Users group is named for some reason differently?

Thanks!

**Comment by dahall** [comment]
Your code to define the task looks correct. To get the name of the Users group, you'll need to use a library or PInvoke call to convert the well known SID for that group to the name.

**Comment by vlad-nica** [comment]
I just bumped in a very weird behavior. 
So the task is registered on "Users" group (for now the group is specified through that magic string).
There are 2 users in the system (for simplicity will call it user1 and user2). The task was created when user1 was signed in. Now after restarting the computer, and signing in again with user1, I noticed that the task is running under user2. Is this a correct behavior? Is it me not understanding properly LogonTrigger?

**Comment by dahall** [comment]
That doesn't match what I'd expect either. The account to which you're logged in only affects the permission to create tasks. The account under which a task runs is specified by the RegisterTaskDefinition parameters. What I don't know is if Windows requires a user account to run a task when a Group is specified. If a group arbitrarily selects one of its members as the process owner, that could explain what you're seeing. I honestly just don't know.

**Comment by dahall** [comment]
On your localized name question, use the [LookupAccountSid ](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-lookupaccountsida) function after creating a `SID` using [ConvertStringSidToSid](https://docs.microsoft.com/en-us/windows/desktop/api/sddl/nf-sddl-convertstringsidtosida) using `S-1-5-32-545` as the string SID.

**Comment by vlad-nica** [comment]
For getting the localized name for the builtin Users group i ended up using:
```
public string GetGroupNameFromSID(string sid)
        {
                return new SecurityIdentifier(sid)
                    .Translate(typeof(System.Security.Principal.NTAccount))
                    .ToString();
        }

GetGroupNameFromSID("S-1-5-32-545");
```

Regarding the process owner not being the user that just logged on, i will try changing the TaskLogonType while keeping the `taskDefinition.Principal.GroupId` set to the "BUILTIN\\Users" (or whatever the GetGroupNameFromSID mentioned above would return) and see what I get.

Do you want me to keep the issue open and let you know my findings?

**Comment by dahall** [comment]
Yes, please.

**Comment by dahall** [comment]
What did you discover after more trials?

**Comment by vlad-nica** [comment]
Ok. So it turns out that when `LogonTrigger` is used, a random user is used from the group in order to run the task. Was unable to find the root cause.
In order to obtain the expected behavior I switched to SessionStateChangeTrigger like 
```
new SessionStateChangeTrigger() { StateChange = TaskSessionStateChangeType.SessionUnlock }
```
Still running tests but till now it seems that the task is ran under the user that logs in/unlocks the session. Will come back if finding something new.

Thanks for you help!
