### ISSUE TITLE
No events in TaskEventWatcher

### ISSUE THREAD

**Issue by Weltraumputze** [dahall/TaskScheduler#811]
Currently im unable to track events with the TaskEventWatcher. Even the sample TestTaskWatcher.zip does not deliver any event entries for my system.

Im working on a Win10 machine. Ver: 1803 (Build 17234.829)
Im using TaskSheduler .NuGet package in Version 2.8.11.

Maybe i have to activate something to be able to track events (Task History)?
I tried it with differend approaches:
Only watching folder, only watching task.
Filtering events, removing filter. etc:

current implementation:
 
      using (TaskService ts = new TaskService())
            {
                TaskFolder folder;
                folder = ts.GetFolder(@"\" + ScheduledTaskConstants.TaskFolder);
                watcher = new TaskEventWatcher(folder);
                //watcher.Filter.EventLevels = new int[] {0};
                
                //watcher.Filter.TaskName = t.Name;
                watcher.EventRecorded += Watcher_EventRecorded;
                watcher.IncludeSubfolders = true;
                watcher.SynchronizingObject = ui;
                watcher.Enabled = true;
            }

The eventrecorded method gets never triggered. As it is not triggered in the TestTaskWatcher.zip
Any ideas?

**Comment by dahall** [comment]
The code for the TestTaskWatcher was out of date, so that .zip file is now updated. The code you're running disposes the `TaskService` instance after the watcher is instantiated thereby rendering it useless. Instead of creating a new instance of `TaskService`, use the `TaskService.Instance`. (In your code above, just replace the `ts` variable with `TaskService.Instance`. Are you using the code provided at https://github.com/dahall/TaskScheduler/wiki/EventSamples#task-event-watching?

**Comment by Weltraumputze** [comment]
Thx for updating the TestTaskWatcher.zip!

Before adapting my code, i would like to see the sample work.
Currently it does not deliver any entries.
I have activated the Task History on my machine, to check if the tasks that im watching are generating events.

That is the case:

![image](https://user-images.githubusercontent.com/49833262/59562182-c1250b00-9029-11e9-9f55-920c846b7afc.png)

But no event is shown in TestTaskWatcher.zip.
How i am configuring it (Watch folder with Include subfolders, or watch the task directly) seems to have no effect at all.

Is there something special regarding the generated tasks that i have to be aware of?
Are you receiving entries with the current zip?

**Comment by dahall** [comment]
Telling my instance to watch the root and subfolders, it works every time.

![image](https://user-images.githubusercontent.com/14349943/59565602-f70ac500-9012-11e9-91d0-4d23f40d44a1.png)

**Comment by Weltraumputze** [comment]
That is realy crazy. Not sure what is wrong on my site...
I just close it for now and check on other machines, if this behaviour still exists.
Thx!
