### ISSUE TITLE
Question: How to set TaskService or TaskDefinition with Info

### ISSUE THREAD

**Issue by Torchok19081986** [dahall/TaskScheduler#813]
Hallo, i have some difficulty to set TaskDefinition for some values. 
I have to set Task for Run without UserLogged-In . Second Manupoint, RadioButton, in windows Taskscheduler at first Tab and add domain admin as User Account to TaskDefinition. I tried to use Example for TaskSecurity, but Dialog for Username and passwird doesnt show it self. 
I use Visual Studio 2019 and .NET Framework 4.7 . Targetsystem : windows Server 2012 R2 and 2016. Loggedin as Domain Admin. 
Can someone help me with to solve this ?

**Comment by dahall** [comment]
Are you trying to create or edit a task using the TaskPropertiesDialog? If so, please supply a screenshot of the settings that are not working. If you are trying to mimic the behavior of settings in the UI using the library, please indicate that and provide the screenshots. I could not understand your request as stated.

**Comment by Torchok19081986** [comment]
Hallo, I try to create new Task for my.exe in msi Installer.  My code for TaskService looks following : 
 ```csharp
TaskDefinition td = TaskService.Instance.NewTask();
                td.RegistrationInfo.Description = "Packages Download";
                td.Principal.LogonType = TaskLogonType.InteractiveToken;
                DailyTrigger dt = (DailyTrigger)td.Triggers.Add(new DailyTrigger(1));        
                td.Settings.DisallowStartIfOnBatteries = true;
                td.Settings.Enabled = false;
                td.Settings.ExecutionTimeLimit = TimeSpan.FromHours(2);
                td.Settings.Hidden = false;
                td.Settings.IdleSettings.RestartOnIdle = false;
                td.Settings.IdleSettings.StopOnIdleEnd = false;
                td.Settings.Priority = System.Diagnostics.ProcessPriorityClass.Normal;
                td.Settings.RunOnlyIfIdle = false;
                td.Settings.RunOnlyIfNetworkAvailable = false;
                td.Settings.StopIfGoingOnBatteries = false;
                td.Principal.RunLevel = TaskRunLevel.Highest;            
                td.Settings.AllowDemandStart = true;
                td.Settings.AllowHardTerminate = true;
                td.Settings.Compatibility = TaskCompatibility.V2;
                td.Settings.MultipleInstances = TaskInstancesPolicy.StopExisting;
                td.Settings.StartWhenAvailable = true;
                td.Settings.WakeToRun = false;
                td.Actions.Add(new ExecAction(exepath, args, workingdir));
                const string taskName = "Serverupdater";       
                TaskService.Instance.RootFolder.RegisterTaskDefinition(taskName, td);
 ```
Sorry, i dont have a screenshot 
For the first one : i only need to know, how to set runcontext for Task . Currently , with code from above, Task will be created as local Administrator, but i need to set User/Groups for Task as Domain Administrator Account. 
Second one, was my mistake. I dont use dialog for User and Password.  I already logged in as Domain Administrator.

**Comment by dahall** [comment]
Everything as you have, except remove setting `td.Principal.LogonType` and change the registration to:
```cs
TaskService.Instance.RootFolder.RegisterTaskDefinition(taskName, td,
   TaskCreation.CreateOrUpdate, "userDomain\\userName", "userPassword",
   TaskLogonType.Password);
```

**Comment by Torchok19081986** [comment]
Many thanks, @dahall. I going to use it in my installer.  Last question: how do i create Settings, that Task schould be run also if user not logged-in . Currently, Task will be create "Run if user logged-in".
Just tested it. It works like expected.
