### ISSUE TITLE
RunOnlyIfLoggedOn property in fluent syntax

### ISSUE THREAD

**Issue by Shakebag** [dahall/TaskScheduler#814]
I found where I can set TaskDefinition.RunIfOnlyLoggedOn property in the normal syntax, but I prefer to use the fluent syntax and it would be really nice to be able to set that property.  If I'm just missing something, my mistake.

EDIT: Been going around in circles on this so I must be missing something obvious.  I can't use featuer/property in my current environment anyway, but I still can't figure out how to get it to run without being logged on.

**Comment by dahall** [comment]
The `RunIfOnlyLoggedOn` property is only viable on pre-Vista systems. For modern versions of Windows, you must register the task using the `TaskLogonType.InteractiveToken` flag. You can find an example towards the bottom of https://github.com/dahall/TaskScheduler/wiki/Examples#complex-example.

Per your suggestion, I have updated the Fluent syntax to allow this. There is now an `AsTask` overload that matches the parameters of `TaskFolder.RegisterTaskDefinition`. Now knowing that at least one person is using the fluent model, I have updated that syntax to support task settings via the `When` term. All this will show up with the next release once I have completed testing.

**Comment by dahall** [comment]
Added in 2.8.13
