### ISSUE TITLE
Extract all the tasks of all computers inside a network using a "Master" computer.

### ISSUE THREAD

**Issue by 0Mp30** [dahall/TaskScheduler#821]
Hello David

There is a way to extract all the scheduled tasks from all the computers inside a network from a master computer?

I want to list all the tasks inside my network (all the tasks in all the computers) to monitoring some important thing.

Thanks in advance.

**Comment by dahall** [comment]
If you are building with .NET 4.5.2 or later, you can use [snapshots ](https://github.com/dahall/TaskScheduler/wiki/Snapshots-and-Multi-threading#snapshots) to capture the information from a single machine to .zip file which can then be used to enumerate all the tasks on that server. Still a bit manual, but that should help.

**Comment by 0Mp30** [comment]
Thanks David for your soon reply, I'll work with snapshots.

**Comment by dahall** [comment]
I'll leave this open for a while in case you have questions or issues.

**Comment by dahall** [comment]
How's your effort progressing?
