### ISSUE TITLE
always this exception The user name or password is incorrect   TaskService

### ISSUE THREAD

**Issue by pichayean** [dahall/TaskScheduler#823]
please solve me.

when i connect to remote server by administrator user

 TaskService ts = new TaskService("SL-SERVER", ".\administrator", "xxxx.xxxx", "xxxxxx", true)

always this exception
System.ComponentModel.Win32Exception: 'The user name or password is incorrect'

how i do. to connect server for read task schedule.

**Comment by dahall** [comment]
Are you trying to use the Administrator account of the remote system? In that case, specify the machine name as the domain (e.g. "SL-SERVER\\Administrator"). Also, don't forget that C# requires double backslashes to indicate the backslash between the domain and user name. I would also not use `true` as the final parameter unless the remote system is older than Windows Vista.

**Comment by pichayean** [comment]
1) i use Administrator account of the remote.
2) when i not use true in last parameter then it error always.

System.UnauthorizedAccessException: 'Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))'

The username and password can access on remote desktop to remote server.

my client windows 10
my remote server windows server 2012R


![Uploading image.png…](https://i.ibb.co/MZd8h1j/1565838032368.jpg)

![Uploading image.png…](https://i.ibb.co/4K6bdhN/Capture3.png)

![Uploading image.png…](https://i.ibb.co/qM5RG1D/Capture4.png)

![Uploading image.png…](https://i.ibb.co/qgg5pt9/Capture6.png)

How i do to connect to remote server. Please help me.
Thank you.

**Comment by dahall** [comment]
Have you been through the content on the wiki page regarding remote server connection and all that has to be enabled on the remote server? Have you run the troubleshooting tool from the homepage? Have you looked at all of the other posts and their resolutions in this issues log? If you've gone through all that and still cannot connect, please let me know.

**Comment by pichayean** [comment]
i try to do by solution i find on internet. but not solve this problem.

i follow this link 
https://github.com/dahall/TaskScheduler/issues/807
but not solve my problem.

**Comment by pichayean** [comment]
in the remote server i'm enabled remote connection.

**Comment by pichayean** [comment]
In all of your questions, I've done it.

**Comment by Chaosology-Asartheen** [comment]
[browser] The path 'C:\Users\chaospc1\Downloads\cefsharp.winforms.75.1.141' for the selected source could not be resolved.


cannot able to install in visual studio 2019

**Comment by pichayean** [comment]
@asartheen-chaosa  Thank you.

**Comment by dahall** [comment]
@asartheen-chaosa: That file is not related in any way to this library.

**Comment by Fenix-Z** [comment]
> 
> In all of your questions, I've done it.

@pichayean Please can you tell me how did you done connection to your local account? I'm dealing with the same problem.

**Comment by Fenix-Z** [comment]
> In all of your questions, I've done it.

@pichayean Please can you tell me how did you done connection to your local account? I'm dealing with the same problem.

**Comment by dahall** [comment]
Have you been able to resolve your issue?

**Comment by pichayean** [comment]
My problem is with remote-server permission. Solved the problem by allow client access.

thk for support.
