### ISSUE TITLE
How to obtain real (/internal) status of scheduled Task at UI application!?

### ISSUE THREAD

**Issue by dsingh-deep** [dahall/TaskScheduler#825]
Hello,

I am trying to use Microsoft.Win32.TaskScheduler to add tasks to Scheduler from my wpf application.

Code I used:
Microsoft.Win32.TaskScheduler.TaskService.Instance.AddTask("SAMPLE Task", new DailyTrigger { DaysInterval = 2 }, new ExecAction("notepad.exe", "c:\\test.log", null));

After task is added to the Window Task Scheduler window, I want to read this Task's status and messages , so that I can update my wpf application entry accordingly!
As an example I tried running a Scheduled Task with an invalid file (e.g. notepad.exe "C:\BadFilePathHere.txt"). When I query the TaskService api it just returns 'Ready' state. If we see some of the event logs the error code in one of them is 2147942402 . How can I get the actual (internal) state in c# !?
Thank you.

**Comment by dahall** [comment]
Does the error show up in the task's property `LastTaskResult`? If the ExecAction ran without error, this should be `0`, other with last error. As you noted, the `State` property will only show the task's operational state.

If you do want to dive into the event log's detail for a task, you can call the `TaskService` instance's `GetEventLog` method with the path of the task (e.g. `task.Path`). It returns a class that allows for the enumeration of the last events associated with the specified task. There is sample code in the documentation for `TaskEventLog`.

**Comment by dsingh-deep** [comment]
dahall: Thanks a lot for the reply. :)

I see that there is an example like:
 ```
foreach (TaskEvent ev in log)
      {       
        if (ev.StandardEventId == StandardTaskEventId.TaskDeleted)
          Console.WriteLine($"  Task '{ev.TaskPath}' was deleted");       
        else if (ev.EventId == 201)
          Console.WriteLine($"  Completed action '{ev.DataValues["ActionName"]}', ({ ev.DataValues["ResultCode"]}) at { ev.TimeCreated.Value}.");
}
```
But, how to get the 'ResultCode' (& result's message) property directly in C# code. Do we have any structure or Enum for it. So that i can write switch-cases based on the error codes and (get message 
 e.g. if there is that missing file ) take appropriate actions on UI !?

**Comment by dahall** [comment]
I think the LastTaskResult is the best way
