### ISSUE TITLE
Scheduled task shows (flashing) command prompt

### ISSUE THREAD

**Issue by dsingh-deep** [dahall/TaskScheduler#827]
I am creating a scheduler task using any of these methods below , but I am not able to prevent the command prompt from flashing..

1)
` 
using (TaskService ts = new TaskService())
     {
        TaskDefinition td = ts.NewTask();

        Microsoft.Win32.TaskScheduler.DailyTrigger wt66 = new DailyTrigger(daysInterval:2); 
     
        td.Principal.LogonType = TaskLogonType.InteractiveToken;
       
        td.Triggers.Add(wt66);

        td.Actions.Add(@"C:\bin\python.exe", @"C:\Users\MyFile.py"); 
       
        ts.RootFolder.RegisterTaskDefinition("Test Task", td,TaskCreation.CreateOrUpdate,null, null,TaskLogonType.InteractiveToken);

      }
`

2)
`
using (TaskService ts = new TaskService())
      {
        TaskDefinition td = ts.NewTask();

        Microsoft.Win32.TaskScheduler.DailyTrigger wt66 = new DailyTrigger(daysInterval:2);    
  
       td.Principal.UserId = "SYSTEM";   

        td.Triggers.Add(wt66);

        td.Actions.Add(@"C:\bin\python.exe", @"C:\Users\MyFile.py");
      
        ts.RootFolder.RegisterTaskDefinition("Test Task", td);
      }
`

3) [Always Access DENIED Exception]
```
Microsoft.Win32.TaskScheduler.TaskService.Instance.AddTask("Test_Task", trigg,
          new Microsoft.Win32.TaskScheduler.ExecAction(@"C:\bin\python.exe",
            @"C:\Users\MyFile.py"),
           null, null, TaskLogonType.S4U, "YAY");
```

Am I doing something wrong!  Any help is greatly appreciated. Thanks..

**Comment by dahall** [comment]
I'm afraid this is the nature of running the task in the user session. There are two ways to get around this:
1) Schedule the task as an account other than the user (SYSTEM, etc.) like your #2 but specify `ServiceAccount`:
```cs
ts.RootFolder.RegisterTaskDefinition("TaskName", td, TaskCreation.CreateOrUpdate,
   "SYSTEM", null, TaskLogonType.ServiceAccount);
```
2) Run `pythonw.exe` instead of `python.exe`

**Comment by dsingh-deep** [comment]
dahall : Thanks for your reply.

I used the 2nd option and it _worked_ amazingly well.  Great . Thanks.

As per the 1st option: I tried
```
Microsoft.Win32.TaskScheduler.TaskService.Instance.AddTask("Test", dt,
                new Microsoft.Win32.TaskScheduler.ExecAction(@"C:\envs\pythonw.exe"
                    , @"E:\PythonScripts\PythonTest.py", null)
                ,"SYSTEM", null, TaskLogonType.ServiceAccount);
```
This gives an Access Denied if I don't run my visual studio in Administrator mode.

ByPassing that, the task returns an error saying..
Task Scheduler successfully completed task "\Test" , instance "{ceea5e38-7c7b-41c3-8f27-4c2110687515}" , action "C:\envs\python.exe" with return code **2147942401**.

**Comment by dahall** [comment]
`TaskService.Instance` effectively is creating a static instance of `new TaskService()` which is current user credentials on local machine. How `TaskService` is created determines the rights for adding tasks. Please see the [Wiki](https://github.com/dahall/TaskScheduler/wiki/TaskSecurity) for more information on rights.

**Comment by dsingh-deep** [comment]
Thank you. :)
