### ISSUE TITLE
TaskSettings.DeleteExpiredTaskAfter Property on Windows Server 2016

### ISSUE THREAD

**Issue by MrCozie** [dahall/TaskScheduler#840]
**Describe the bug**
I'm unable to get the property "DeleteExpiredTaskAfter" working on Windows Server 2016.
The expired task is not being removed.

**To Reproduce**
I've tried to keep the code as close as possible to the exampled version;
* The code below has been used on Windows 10, Windows Server 2012 and Windows Server 2016.

```c#
// Create a new task definition and assign properties
TaskDefinition td = TaskService.Instance.NewTask();
td.RegistrationInfo.Description = "Test DeleteExpiredTaskAfter";
td.Principal.LogonType = TaskLogonType.InteractiveToken;
td.Settings.DeleteExpiredTaskAfter = TimeSpan.FromSeconds(1);
td.Settings.ExecutionTimeLimit = TimeSpan.FromSeconds(15);

// Add a TimeTrigger 
td.Triggers.Add(new TimeTrigger
{
	StartBoundary = DateTime.Now + TimeSpan.FromSeconds(10),
	EndBoundary = DateTime.Now + TimeSpan.FromSeconds(15)
});

// Add an action that will display a message whenever the trigger fires
td.Actions.Add(new ShowMessageAction("Test DeleteExpiredTaskAfter", "Info"));

// Register the task in the root folder
const string taskName = "Test DeleteExpiredTaskAfter";
TaskService.Instance.RootFolder.RegisterTaskDefinition(taskName, td);
```

**Expected behavior**
Gets and sets the amount of time that the Task Scheduler will wait before deleting the task after it expires. A TimeSpan value of 1 second indicates the task is set to delete when done. A value of TimeSpan.Zero indicates that the task should not be deleted.

**Screenshots**
Not available

**Environment (please complete the following information):**
Task Scheduler: 2.8.17
- Host: Windows Server 2012 [code works]
  - TaskService.Instance.HighestSupportedVersion=1.4
- Host: Windows Server 2016 [code doesn't work]
  - TaskService.Instance.HighestSupportedVersion=1.5
- Host: Windows 10 [code works]
  - TaskService.Instance.HighestSupportedVersion=1.6

**Additional context**
As always it may be the person on the chair who misunderstands the situation, but when I see the code work on an older AND a newer environment it seems worth investigating to me.

**Comment by dahall** [comment]
Very interesting, especially given the different outcomes on different versions. I just gave the code a quick look. I'm concerned this may be a Microsoft problem since this library does not treat that property differently based on OS version. I'll do some further testing and report back my findings.

**Comment by dahall** [comment]
After testing on many platforms, it appears this is a bug only in Windows Server 2016's native Task Scheduler COM library. I unfortunately cannot work around it. I have tested this using my library, native COM code in C++ and PowerShell scripting all with the same result. It is definitely a problem in the OS. If critical, I would suggest reporting this as a bug to Microsoft telling that on Windows Server 2016, the Task Scheduler library 1.5 does not delete the task after execution when using ITaskService::put_DeleteExpiredTaskAfter set to "PT0S" regardless of the EndBoundary value set on the trigger.

I'm installing all the updates on my in WS2016 instance and will retest. If the updates fix the problem, I'll repost with the update.

**Comment by MrCozie** [comment]
Thank you for your time and efforts.
I've logged a case at Microsoft.

Commercial support team: +44 (0)344 800 2400
Case: 1488600144
