### ISSUE TITLE
New Task Create in a folder

### ISSUE THREAD

**Issue by renehartman73** [dahall/TaskScheduler#842]
Hey Dahall,

There is a issue with the dll.

Problem:
Create a new Task Scheduler Library and it works fine!
Create a new Task in a folder and it does not create a new task.

Did you know this and can you fixed this?

Greetings,
René

**Comment by dahall** [comment]
I'm not sure I understand your issue. If you look at the code for [Complex Example](https://github.com/dahall/TaskScheduler/wiki/Examples#Complex-example), it creates a task in the root folder, the creates a folder and adds a new task to that folder. If that's not the problem, please include a code snippet of the action that is failing along with the exception that is thrown.

**Comment by renehartman73** [comment]
Hey David,

Can you try this:

[cid:image001.png@01D5B68C.27FF5820]


Create new Task in Task Scheduler Library, Task name is RENE this work good!
[cid:image002.png@01D5B68C.99D22360]


Create new Task in a folder:
[cid:image003.png@01D5B68C.99D22360]

[cid:image004.png@01D5B68C.99D22360]

No Task wil created and no error!


Hopende u voldoende te hebben geïnformeerd.

Met vriendelijke groet / Kind regards,
René Hartman

Van: David Hall <notifications@github.com>
Verzonden: donderdag 19 december 2019 15:37
Aan: dahall/TaskScheduler <TaskScheduler@noreply.github.com>
CC: Rene Hartman | Vector Eyes <rene.hartman@vectoreyes.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [dahall/TaskScheduler] New Task Create in a folder (#842)


I'm not sure I understand your issue. If you look at the code for Complex Example<https://github.com/dahall/TaskScheduler/wiki/Examples#Complex-example>, it creates a task in the root folder, the creates a folder and adds a new task to that folder. If that's not the problem, please include a code snippet of the action that is failing along with the exception that is thrown.

**Comment by dahall** [comment]
None of your images can be viewed so I cannot determine what you are showing me. Please repost with pictures that are added as files by dragging them into the window.

**Comment by renehartman73** [comment]
![02-NewTaskWithNameReneCreate](https://user-images.githubusercontent.com/54589740/71239573-2d4d3800-2307-11ea-8953-f725965177e2.JPG)
![03-CreateNewTaskInFolder](https://user-images.githubusercontent.com/54589740/71239575-2d4d3800-2307-11ea-8eeb-8a21016354e5.JPG)
![04-CreateNewReneTaskInFolder](https://user-images.githubusercontent.com/54589740/71239577-2d4d3800-2307-11ea-882e-5a2bcfa1fd6c.JPG)
![01-CreateNewTask](https://user-images.githubusercontent.com/54589740/71239580-2de5ce80-2307-11ea-8e84-1855f414e722.JPG)

Hey David,

Next try :D

Can you try this!

Create with your demo TaskSchedulerMockup a new task in the Task Scheduler Library. (Picture 01)

This work great, Picture 02.

But, when you create a same task in a folder (Picture 03) then it dont work any more. (Picture 04).

This was working in the previous one, but i think Windows make a update in the Windows Task Scheduler.


I hope it is clear now.

Best regards,

René Hartman

**Comment by dahall** [comment]
Thank you for the pictures. I have confirmed that TaskSchedulerMockup fails to create a task in any non-root folder. This is not a problem with the underlying library as I am able to do this in my unit tests. I'll look at the demo code and see if I can fix the problem.

**Comment by dahall** [comment]
Fixed in 2.8.18, just released.

**Comment by dahall** [comment]
Please confirm I've fully addressed your issue once you've tested the new version.

**Comment by renehartman73** [comment]
I'm on vacation now, I'll let you know.

Met vriendelijke groet,
Vector Eyes B.V.

René Hartman

Verstuurd vanaf mijn iPhone

Op 21 dec. 2019 om 16:54 heeft David Hall <notifications@github.com> het volgende geschreven:

﻿

Please confirm I've fully addressed your issue once you've tested the new version.

**Comment by renehartman73** [comment]
Happy new year!
Thanks, It works fine.
