### ISSUE TITLE
RunOnlyIfLoggedOn not working?

### ISSUE THREAD

**Issue by 0Mp30** [dahall/TaskScheduler#843]
Hello @dahall 

I trying to create a new task even if the system if logged or not but I'm getting an error and I'm not sure how to proceed.  Could you help / guide me?

Thanks in advance.

**Screenshots**
![image](https://user-images.githubusercontent.com/29720202/74990343-0bf4ef00-5411-11ea-8f05-399177d03667.png)

Needed option
![image](https://user-images.githubusercontent.com/29720202/74990428-57a79880-5411-11ea-80f2-34554edf2ee0.png)

**Comment by dahall** [comment]
Please search issues before posting. This is mentioned multiple times. See #753.

**Comment by 0Mp30** [comment]
Tks @dahall
