### ISSUE TITLE
Task Scheduler allows creation with out of bounds date

### ISSUE THREAD

**Issue by xantari** [dahall/TaskScheduler#845]
If you create a task with an end boundary as follows:

trigger.EndBoundary = New DateTime(9999, 12, 31)

It will work, but when you try to open the created task within Task Scheduler and click on Triggers tab. Then clicked on Edit.

You get this:

![image](https://user-images.githubusercontent.com/6610039/75122253-61bfd600-5661-11ea-84cd-232cef1024a7.png)

Then this:

![image](https://user-images.githubusercontent.com/6610039/75122259-6ab0a780-5661-11ea-8225-d2cb979b208c.png)

**Comment by dahall** [comment]
I'm afraid this is a bug with the Task Scheduler MMC app and not this library.

**Comment by xantari** [comment]
Should the library allow creation of those dates when the Task Scheduler UI only allows it to go to 12/31/9998 ?

![image](https://user-images.githubusercontent.com/6610039/75128537-2ede0800-568a-11ea-985a-63e23bae4b15.png)

When expiration is not defined it seems then 12/31/9999 11:59:59 PM is then allowed, but not 12/31/9999 12:00:00AM for some reason.

**Comment by dahall** [comment]
Given that there is no documentation that even limits the dates supported by the native COM interfaces around which this wrapper library is based, my inclination is not change the functioning of the library in case MS fixes their UI bugs at some point. I'd rather document the condition that you've found in the property documentation. Does that sound reasonable?

**Comment by xantari** [comment]
Sounds good!
