### ISSUE TITLE
Not able to create task using Managed Service account by passing xml payload

### ISSUE THREAD

**Issue by Venkatesh-Appala** [dahall/TaskScheduler#848]
I get below error when I try to create task using Managed Service account by passing xml payload. Any help appreciated!!

<img width="915" alt="2020-03-10 13_57_25-Photos" src="https://user-images.githubusercontent.com/49491498/76579761-9f5a9680-648a-11ea-85b7-757a397a8c9b.png">

**Comment by dahall** [comment]
That means you have an error on line 40 of your xml

**Comment by Venkatesh-Appala** [comment]
Thanks a lot for the response. Attached is the xml used. I don’t see ay error. Please help me.

Thanks
Venkatesh Appala

**Comment by Venkatesh-Appala** [comment]
Attaching file here
[Test.txt](https://github.com/dahall/TaskScheduler/files/4327418/Test.txt)

**Comment by dahall** [comment]
This XML includes a `<LogonType>Password</Password>` tag. Registering this will fail since it requires new credentials to be entered.

**Comment by Venkatesh-Appala** [comment]
Thanks for the response. If I am using MSA account, what should be my LogonType? I use the same LogonType as Password when I am registering task using SchTasks.exe. But the same is not working with Task Scheduler dll. 

I tried with Log on Type as Service Account as well. Error changed and its showing error in the LogonType line.

**Comment by dahall** [comment]
See if #820 or #350 help you.

**Comment by Venkatesh-Appala** [comment]
Thanks. LogonType.None worked for my MSA account.
