### ISSUE TITLE
TaskSchedulerEditor 2.8.20 has wrong version package reference to AeroWizard and TimeSpan2

### ISSUE THREAD

**Issue by vfofanov** [dahall/TaskScheduler#852]
**Describe the bug**
The package TaskSchedulerEditor 2.8.20 has different version of package and reference in compiled assembly
for AeroWizard and TimeSpan2

During the build assembly with TaskSchedulerEditor package installed you got next warnings:

warning MSB3277: Found conflicts between different versions of "AeroWizard" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
warning MSB3277: Found conflicts between different versions of "TimeSpan2" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
  
**To Reproduce**
1. Create assembly with installed TaskSchedulerEditor 2.8.20 as PackageReference
2. Run Build
4. See warnings in Output window

**Expected behavior**
Fix packages version in nuspec file and redeploy nuget package to Nuget.org

**Additional context**
Thank you for your great work!

As workaround you can explicit install AeroWizard and TimeSpan2 with correct versions

**Comment by dahall** [comment]
Thanks for reporting this. It is fixed in 2.8.21, just pushed.
