### ISSUE TITLE
Is there a compiled executable which can be used by ordinary user as a drop-in replacement for the terrible default windows task scheduler UI?

### ISSUE THREAD

**Issue by WestXu** [dahall/TaskScheduler#853]
Man I just hate the built-in old UI interface of task scheduler in modern win10. Can't even move/rename tasks.

Glad to find this project.

**Comment by dahall** [comment]
In the project, there is a [TaskSchedulerMockup](https://github.com/dahall/TaskScheduler/tree/master/TaskSchedulerMockup) subproject that is a rough attempt at mimicking the default UI. I'm in the process of recreating this using XAML controls, but that work is far from done.
