### ISSUE TITLE
Unable to update a task - Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

### ISSUE THREAD

**Issue by arsalansaleem96** [dahall/TaskScheduler#855]
In windows I have created task scheduler with trigger "At system startup". Now I'm trying to update the taskDefinition using `task.RegisterChanges();` 
It's giving me this exception Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

The scheduler was created using Admin account and I'm using the same account to update the scheduler.

**Comment by dahall** [comment]
`RegisterChanges` will fail if the task was created with a password. Is that the case here?

**Comment by arsalansaleem96** [comment]
No it's not created with password. I have also posted on [stackoverflow](https://stackoverflow.com/questions/64274834/unable-to-update-a-task-using-task-scheduler-wrapper).

**Comment by dahall** [comment]
Have you looked at the examples in the Wiki and in about 20 other closed issues? This is a very common problem with a variety of fixes depending on your environment. I'd start with #782.

**Comment by arsalansaleem96** [comment]
Yess I have tried different solutions. I gave all the security permissions . Also, I have tried just assigning the new action to the position of the old one as you mentioned above [#782](https://github.com/dahall/TaskScheduler/issues/782) . Unfortunately, the issue still there.

![image](https://user-images.githubusercontent.com/13997274/98520533-15a5d780-226a-11eb-96c7-b137de0cf7f3.png)

I am getting this exception. 

![image](https://user-images.githubusercontent.com/13997274/98520604-2eae8880-226a-11eb-829f-703e966e97d3.png)

You can also see stacktrace.

![image](https://user-images.githubusercontent.com/13997274/98520679-4d148400-226a-11eb-876a-733901651a18.png)

**Comment by dahall** [comment]
Were you able to work around your issue?
