### ISSUE TITLE
Synchronize Between Time Zones Setting?

### ISSUE THREAD

**Issue by m-horne** [dahall/TaskScheduler#861]
Not sure if this is available in the interface or not, but is it possible to check or uncheck the "Synchronize Between Time Zones Setting" that is located on the "Edit Trigger" dialog (in the UI in Task Scheduler) when programmatically defining the trigger?  

It appears that it defaults to checked which causes some of our 12:01AM tasks to run at 11:01PM because of the end of daylight savings time.

Thank you!

**Comment by dahall** [comment]
See issues #423, #173 for your answer

**Comment by m-horne** [comment]
Thank you
