### ISSUE TITLE
Windows Defender antivirus alert for Microsoft.Win32.TaskScheduler

### ISSUE THREAD

**Issue by loperto** [dahall/TaskScheduler#862]
I created a simple application in net 5 that uses this library to schedule another application's update check.
But after building the application windows defender detects a threat with Microsoft.Win32.TaskScheduler library:
![image](https://user-images.githubusercontent.com/7349520/101216281-87155200-367f-11eb-8cf0-6c4b597447d3.png)
I have removed the TaskScheduler library from the project and win defender finds no threats.

Any ideas?

**Comment by dahall** [comment]
This seems to happen with each new framework I add to the library. This is scanned with two AV scanners before pushing as well as through a code analyzer for security weaknesses. If you choose "Allow on device" it reports back to Microsoft. I'll also submit it to them for review. Thanks for the heads up. This doesn't happen on my dev/test machine.

**Comment by dahall** [comment]
I just pushed an update (2.9.0). Will you try it and let me know if it produces the errors you reported?

**Comment by loperto** [comment]
Very strange: now with same old version 2.8.21 i have no threats. I had not allowed the previous version of my application in windows defender.
It's possibile that microsoft updates have fixed it?

**Comment by dahall** [comment]
Yes. I submitted it to MS for review.

**Comment by loperto** [comment]
Ok great! thank you @dahall  for your support! ;)
