### ISSUE TITLE
WCF Service Reference not working with TaskScheduler

### ISSUE THREAD

**Issue by krislechy** [dahall/TaskScheduler#865]
WCF Service Reference not working with Task Scheduler, namespace issue, not defined.
Example causes CS0246 because an object of type Type was used where an actual type was expected.

**Comment by dahall** [comment]
Please provide a lot more information. As written, your issue is not actionable.

**Comment by krislechy** [comment]
> Please provide a lot more information. As written, your issue is not actionable.

After Update VS2019, i have problem to define namespace of my ServiceModel, Generates Thousands of Errors in Reference.cs, after deleted "TaskScheduler" it work fine.
![image](https://user-images.githubusercontent.com/20987251/101786840-78abb800-3b0f-11eb-967d-d8b62234da4b.png)

**Comment by dahall** [comment]
This library has nothing to do with WCF and has no dependencies on external libraries. I am unable to translate the errors you posted in the picture. Even with 18 years of experience supporting this library, I have no idea what could be causing your problem and actually doubt it is this library. I would check what has changed with Visual Studio with the update.

**Comment by krislechy** [comment]
> This library has nothing to do with WCF and has no dependencies on external libraries. I am unable to translate the errors you posted in the picture. Even with 18 years of experience supporting this library, I have no idea what could be causing your problem and actually doubt it is this library. I would check what has changed with Visual Studio with the update.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246
WPF Application actually. Do you have any suggestions else?

**Comment by dahall** [comment]
That error appears to come when you have not referenced an assembly correctly. I would try adding the NuGet package back into your project and then ensure that it is referenced per the instructions in the link you just sent.

**Comment by krislechy** [comment]
> That error appears to come when you have not referenced an assembly correctly. I would try adding the NuGet package back into your project and then ensure that it is referenced per the instructions in the link you just sent.

It didn't work for me
In the list of the all namespaces there is also no link on ServiceModel.
I forgot to say that with the new update, the visual studio was installed the net5, perhaps this is somehow related.

**Comment by dahall** [comment]
I'm not sure what "ServiceModel" is and this library doesn't interact with anything by that name. This library supports all versions of .NET (Framework, Core, Standard) including .NET 5.0.

**Comment by krislechy** [comment]
Ok, thanks, I will look for another solution.
