### ISSUE TITLE
How to send automated mail

### ISSUE THREAD

**Issue by cuongpv88** [dahall/TaskScheduler#868]
Hi, I want to use TaskScheduler in my Blazor project. There are ways to implement automatic mailing of user notifications.
Thanks

**Comment by dahall** [comment]
The Windows Task Scheduler allows you to send a fixed email message to a fixed recipient based on a system trigger. It uses PowerShell to actually perform the email action. Unless you need to react to a system event, I would encourage you to look at other SMTP libraries or PowerShell to do mailing.

**Comment by cuongpv88** [comment]
Thanks for your feedback
