### ISSUE TITLE
Does not show all tasks

### ISSUE THREAD

**Issue by lvandenb** [dahall/TaskScheduler#870]
**Describe the bug**
Show all tasks does not list al tasks, but the calling users can see/start  the tasks in the standard windows tool.

**To Reproduce**
Task are run as another account
The calling user is in administrators group .
(So the calling user can start,stop, change process. But not with this library)

**Comment by dahall** [comment]
There are three things that can cause this:
1) The user permissions and UAC of the account running the app
2) The user permissions of the account passed to the `TaskService` constructor
3) Permissions on the tasks themselves

Given what I could understand of your post, I would check UAC when the person in the Administrators group is running the app.

**Comment by Qarj** [comment]
I've just been struggling with too since am running through IIS.

Had to change the Application Pool from `ApplicationPoolIdentity` to `LocalSystem` to get all the tasks to show.
