### ISSUE TITLE
Scheduled Task Creation failed

### ISSUE THREAD

**Issue by puzzled-paradox** [dahall/TaskScheduler#889]
**Describe the bug**
When creating a Windows Scheduled Task, we received an error: " The current version of the native library (1.6) does not support the version of the "[Task Name]" task (0.0)"

**To Reproduce**
In the particular piece of code we are working with, there are two types of actions performed:
1. TaskService.Instance.AllTasks in which it updates a scheduled task's Definition.Settings.ExecutionTimeLimit and Definition.Settings.StartWhenAvailable and then calls RegisterChanges()
2. TaskService.Instance.AddTask in which it creates a new task with additional settings of the Definition.Principal.UserId, Definition.Settings.ExecutionTimeLimit, Definition.Settings.Enabled, and Definition.Settings.StartWhenAvailable and then calls Definition.Triggers.Clear() and RegisterChanges()

**Environment (please complete the following information):**
 - Windows Version: Windows 21H1 19043.1083
 - Library Version: 2.8.4

**Comment by dahall** [comment]
This is curious. I can only guess that there is a task on the machine that, when its XML is requested, returns one without a version tag. The code can be found [here](https://github.com/dahall/TaskScheduler/blob/b85afe17fb51cec0d9b5def2f56cc8595e18548e/TaskService/Task.cs#L1598).

It could be the order or way that you're calling the methods on the retrieved tasks. Do you mind sending your code for the two examples above?

**Comment by puzzled-paradox** [comment]
Sure here is the code from the examples above. 

[TaskScheduler Examples.txt](https://github.com/dahall/TaskScheduler/files/6841585/TaskScheduler.Examples.txt)

**Comment by dahall** [comment]
I've run the following code without errors on my Windows 10 21H1 19043.1110 system with lib version 2.9.2.
```cs
foreach (Task t in TaskService.Instance.AllTasks)
{
   foreach (ExecAction action in t.Definition.Actions.OfType<ExecAction>().
      Where(a => string.Equals(a.Path, cmdPath, StringComparison.InvariantCultureIgnoreCase) &&
         string.Equals(a.Arguments, args, StringComparison.InvariantCultureIgnoreCase)))
   {
      t.Definition.Settings.ExecutionTimeLimit = TimeSpan.FromDays(1);
      t.Definition.Settings.StartWhenAvailable = true;
      t.RegisterChanges();
   }
}
var task = TaskService.Instance.AddTask("Temp", new DailyTrigger(1) { StartBoundary = DateTime.Now },
   new ExecAction(commandProgramPath, args), "SYSTEM", null, TaskLogonType.ServiceAccount);
task.Definition.Settings.ExecutionTimeLimit = TimeSpan.FromDays(1);
task.Definition.Settings.StartWhenAvailable = true;
task.Definition.Triggers.Clear();
task.Definition.Settings.Enabled = false;
task.RegisterChanges();
```

**Comment by dahall** [comment]
@puzzled-paradox  Did the sample code above solve your issue?

**Comment by puzzled-paradox** [comment]
Yes, thank you very much
