### ISSUE TITLE
Show task while running as SYSTEM account

### ISSUE THREAD

**Issue by yingying96** [dahall/TaskScheduler#896]
Hi,

Would like to check how do I run as SYSTEM account while keeping the config of "Run only when the user is logged on"?
I realized that only when i select "Run only when the user is logged on", then the GUI of the exe that i am running appears.

Here's a sample of my code.
```
        static void ScheduleTask(String TaskName, String Date)
        {
            using (TaskService ts = new TaskService())
            {
                TaskDefinition td = ts.NewTask();
                td.RegistrationInfo.Description = TaskName;
                td.Triggers.Add(new TimeTrigger() { StartBoundary = Convert.ToDateTime(Date) });

                td.Actions.Add(new ExecAction(@"%windir%\notepad.exe", null, null));
                // ts.RootFolder.RegisterTaskDefinition(TaskName, td);
                ts.RootFolder.RegisterTaskDefinition(TaskName, td, TaskCreation.CreateOrUpdate, "SYSTEM", null, TaskLogonType.ServiceAccount);
            }
        }
```

**Comment by dahall** [comment]
Those two settings, running as SYSTEM and running when logged in, are mutually exclusive. What you want to do cannot be done.

**Comment by yingying96** [comment]
I see! Then is there a way to run as SYSTEM account but have the GUI of the exe from the task running to show?

**Comment by dahall** [comment]
There is not

**Comment by yingying96** [comment]
Ok thanks!
