### ISSUE TITLE
Add task to folder using TaskEditDialog

### ISSUE THREAD

**Issue by alexdyb** [dahall/TaskScheduler#9]
Hi,
what is the right way to add new task to specific folder using dialog? I use such code to add to root folder, tried to specify editorForm.TaskFolder, but task still created in RootFolder.

Using ts As New TaskService()
Dim td As TaskDefinition = ts.NewTask()
Dim f As TaskFolder = ts.GetFolder(strFolder)
td.Actions.Add(strExeFilename)
Dim editorForm As New TaskEditDialog(ts, td, True, True) 
editorForm.ShowDialog()

Or, perhaps it is possible to move task to other folder?

Alex

**Comment by dahall** [comment]
This is a bug. I would suggest that you use the TaskEditDialog and set the registerOnAccept to 'false'. Then, when the user closes the dialog, use the TaskDefinition property and register it in the folder you desire. I will fix the code so you can set the TaskFolder property and make it work.

**Comment by dahall** [comment]
Fixed (2.6.2)

**Comment by alexdyb** [comment]
Thanks, made it working. But still something wrong there, I have to set:

editorForm.TaskFolder = f.Path

just before 
editorForm.ShowDialog()

else, if I do for example:

editorForm.TaskFolder = f.Path
editorForm.RegisterTaskOnAccept = True
editorForm.Editable = True
editorForm.ShowDialog()

editorForm.TaskFolder reset to empty string.

One note on " I would suggest that you use the TaskEditDialog and set the registerOnAccept to 'false'. Then, when the user closes the dialog, use the TaskDefinition property and register it in the folder you desire" - that was my original idea, but if you have set for a new task "Run whether user is logged or not" - it does not bring a dialog to enter password and .RegisterTaskDefinition() fails. Try to edit task with "Run whether user is logged or not"  and add new task with "Run whether user is logged or not" and you see the difference

**Comment by dahall** [comment]
When you don't use registerOnAccept, you must handle capturing and assigning a password. This is by design.

The order of setting TaskEditorDialog properties, to ensure correct placement is:
1) Task or TaskDefinition
2) Editable
3) TaskName
4) TaskFolder

**Comment by dahall** [comment]
To simplify this in the next release, I have extended the TaskEditDialog constructor to accept an optional task name and task folder. You'll see it's implementation in 2.6.3.

**Comment by dahall** [comment]
To help with the question on prompting for a password, I've added some sample code at the bottom of the [Task Security documentation wiki page](https://github.com/dahall/TaskScheduler/wiki/TaskSecurity).
