### ISSUE TITLE
Add an Example for Trigger.Repetition Property

### ISSUE THREAD

**Issue by pirex360** [dahall/taskscheduler#919]
Please add an example for Trigger.Repetition Property.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://dahall.github.io/TaskScheduler/html/P_Microsoft_Win32_TaskScheduler_Trigger_Repetition.htm

**Comment by dahall** [comment]
See https://github.com/dahall/TaskScheduler/wiki/TriggerSamples
