### ISSUE TITLE
Run Task Every Specific Minutes

### ISSUE THREAD

**Issue by Gorkido** [dahall/taskscheduler#924]
I want to create a task schedule every specified minutes. How to do that?

**Comment by dahall** [comment]
```cs
TimeTrigger tt = new TimeTrigger();
// Set the time in between each repetition of the task after it starts to 30 minutes.
tt.Repetition.Interval = TimeSpan.FromMinutes(30); // Default is TimeSpan.Zero (or never)
// Set the time the task will repeat to 1 day.
tt.Repetition.Duration = TimeSpan.FromDays(1); // Default is TimeSpan.Zero (or forever)
// Set the task to end even if running when the duration is over
tt.Repetition.StopAtDurationEnd = true; // Default is false;
```

**Comment by Gorkido** [comment]
> ```cs
> TimeTrigger tt = new TimeTrigger();
> // Set the time in between each repetition of the task after it starts to 30 minutes.
> tt.Repetition.Interval = TimeSpan.FromMinutes(30); // Default is TimeSpan.Zero (or never)
> // Set the time the task will repeat to 1 day.
> tt.Repetition.Duration = TimeSpan.FromDays(1); // Default is TimeSpan.Zero (or forever)
> // Set the task to end even if running when the duration is over
> tt.Repetition.StopAtDurationEnd = true; // Default is false;
> ```

Thanks
