### ISSUE TITLE
Dependency cycle detected

### ISSUE THREAD

**Issue by ShiZNizZLe** [dahall/taskscheduler#933]
**Describe the bug**
https://docs.microsoft.com/nl-nl/nuget/reference/errors-and-warnings/NU1108

**To Reproduce**
Open vs2022
install nuget package staskscheduler and/or taskschedluereditor
receive errors:
![afbeelding](https://user-images.githubusercontent.com/15122459/152173532-da2ea06a-46ba-4258-86be-b08d83afdf64.png)

**Expected behavior**
installs correctly

**Environment (please complete the following information):**
win10
vs2022 vb.net forms app

**Comment by dahall** [comment]
THis is a typical problem with VS and NuGet. The best course I have found is to clear the NuGet cache from the Tools menu, exit VS, the reload your solution and try again.

**Comment by ShiZNizZLe** [comment]
didn't work unfortunately :/

**Comment by ShiZNizZLe** [comment]
ah it worked now, didnt work because my project was the same name
