### ISSUE TITLE
Must I distribute my app with localization folder?

### ISSUE THREAD

**Issue by gscheartA** [dahall/taskscheduler#936]
TaskScheduler is so great for me to create and run schedule task in my app, but I noticed that some folder(de,es,fr......) were created after building in release config, and each folder contained a file named  "Microsoft.Win32.TaskScheduler.resources.dll".
Actually, **my app just create , run , delete some scheduled tasks** and not do other things related to it. Must I distribute my app with the localization folders? I don't know if the app will work when I just distribute "Microsoft.Win32.TaskScheduler.dll".

**Comment by gscheartA** [comment]
Thanks a lot for your help

**Comment by dahall** [comment]
See #934
