### ISSUE TITLE
Add an Example for ComHandlerAction Class

### ISSUE THREAD

**Issue by pasupuletinaveenkumar** [dahall/taskscheduler#946]
Please add an example for ComHandlerAction Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://dahall.github.io/TaskScheduler/html/T_Microsoft_Win32_TaskScheduler_ComHandlerAction.htm

**Comment by dahall** [comment]
See https://github.com/dahall/TaskScheduler/wiki/ActionSamples#email-message-and-com-object-actions
