### ISSUE TITLE
Issue while running TaskScheduler.cs

### ISSUE THREAD

**Issue by Janani-harshu** [dahall/taskscheduler#949]
error MSB3321: Importing key file "C:\Users\Desktop\TaskScheduler-master\TaskScheduler-master\Microsoft.Windows.TaskScheduler.pfx

May I please know how to resolve this issue?

**Comment by dahall** [comment]
That file is available in the repository. Make sure this file is placed in the directory above.

**Comment by dahall** [comment]
@Janani-harshu Resolved?
