### ISSUE TITLE
TaskScheduler creates folders Locales when build project

### ISSUE THREAD

**Issue by Th3AnG3L** [dahall/taskscheduler#951]
Hello,
Can someone tell me how to get rid from the folders that were created from the TaskScheduler when build the project
it creates folders:
de, es, fr, it, pl, ru, zh-CN, zh-Hant and inside creates file: Microsoft.Win32.TaskScheduler.resources.dll
how i can get rid off this folders?
when i remove the TaskScheduler from Nuget and it stops create this folders
how i can fix this issue to not create any folders to be default (en)

**Comment by Th3AnG3L** [comment]
so i guest this is not fixed in last version, so only option to solve this was to go in my project/packages/TaskScheduler/ and delete from all framework version this folders and when re-build the project not created the folders anymore

**Comment by dahall** [comment]
Those folders hold the localized resources used in string visualization for the library. You can simply delete them if you don't use any `ToString` methods or if you don't expect your application to be used for non-English locales.

**Comment by Th3AnG3L** [comment]
i found out only solution was to delete the folders from package\library\ and leave only what i need then it doesn't create them.. but it should be fixed in base source code of library.

**Comment by dahall** [comment]
There is no fix necessary. This is by design. Those files hold localized strings for various library items.
