### ISSUE TITLE
Add an Example for TaskFolder.DeleteTask Method

### ISSUE THREAD

**Issue by kavya-kg** [dahall/taskscheduler#953]
Please add an example for TaskFolder.DeleteTask Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://dahall.github.io/TaskScheduler/html/M_Microsoft_Win32_TaskScheduler_TaskFolder_DeleteTask.htm

**Comment by dahall** [comment]
See wiki
