### ISSUE TITLE
TaskScheduler 1,000 Stars.

### ISSUE THREAD

**Issue by zulu-caPWN** [dahall/taskscheduler#961]
I haven't used it yet but I'm happy to be the 1,000th star on this repo!  

Congrats to you.

---

![image](https://user-images.githubusercontent.com/15136141/230464353-75230fbf-ebf2-4aa0-b3dd-7a369c9f7910.png)

**Comment by dahall** [comment]
Thank you! I've been periodically maintaining this project now for over 20 years. It is so rewarding to know it is helping other developers.
