### ISSUE TITLE
Cannot create Task within a AWS EC2 machine

### ISSUE THREAD

**Issue by RafaelSolVargas** [dahall/taskscheduler#971]
**Describe the bug**
I'm hosting an .NET Framework 4.8 MVC in a AWS EC2 machine, within it, there is a IIS in front of the application. 

**To Reproduce**
I don't think that it's simple to reproduce, but here is the code:
![image](https://github.com/dahall/TaskScheduler/assets/86136313/b305e08e-e4e5-4db9-96ad-39dd228cb50d)

I added the notepad action just to test. This code works fine when running in localhost, but this error is thrown when running in EC2 
![image](https://github.com/dahall/TaskScheduler/assets/86136313/03231cfd-f0a2-4e95-8aff-2847728ce937)

The message error is: (39,4):Task:

**Expected behavior**
The apps to start executing

**Environment (please complete the following information):**
 - The EC2 runs a Windows Server 2017
 - Library version: 2.10.1

**Comment by dahall** [comment]
This is very likely a permission problem with the OS. Registering tasks requires admin status. See this project's wiki for information about all rights required.

**Comment by RafaelSolVargas** [comment]
I changed the logon type to password and it worked, thanks!
