### ISSUE TITLE
Add an Example for RepetitionPattern Class

### ISSUE THREAD

**Issue by naidu123** [dahall/taskscheduler#974]
Hi, I have a requirement to call a particular method 4 times in a day, that method has implemented inside the application, that application always running in that system as a start up application

TODO (optional): I wanted to execute particular methods in 6 hours once in a day, I am using DailyTrigger which is executing daily at once, but we need to execute methods in 4 times a day.

Please help us to complete this task.

Thanks & Regards
Manjunath
9014950956

Help Topic: https://dahall.github.io/TaskScheduler/html/T_Microsoft_Win32_TaskScheduler_RepetitionPattern.htm

**Comment by dahall** [comment]
There is an example there already. In your case, the interval is 6 hours.
