### ISSUE TITLE
Add an Example for TaskService.FindTask Method

### ISSUE THREAD

**Issue by saqibtechsolab** [dahall/taskscheduler#982]
Please add an example for TaskService.FindTask Method.

If the task is disabled then Task will not find. 
TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://dahall.github.io/TaskScheduler/html/M_Microsoft_Win32_TaskScheduler_TaskService_FindTask.htm

**Comment by dahall** [comment]
See documentation
