### ISSUE TITLE
`TaskDefinition.Settings.Priority` default value NOT `Normal`

### ISSUE THREAD

**Issue by GF-Huang** [dahall/taskscheduler#989]
https://github.com/dahall/TaskScheduler/blob/c126e0c54e9b3393bc753af4ba8214664eb51b0f/TaskService/Task.cs#L3297-L3298

![image](https://github.com/dahall/TaskScheduler/assets/4510984/ee8209ed-8042-478c-b4a4-1bad07ec34a7)

**Comment by dahall** [comment]
This is tied to V1 and V2 compatibility and has changed in recent OS versions. I'd rather not change this since it has been in place for so long and could break existing code.
