### ISSUE TITLE
TaskEditDialog and other Dialog types not found in TaskScheduler namespace

### ISSUE THREAD

**Issue by nahvan9** [dahall/taskscheduler#995]
**Describe the bug**
TaskEditDialog not showing up in TaskScheduler namespace

**To Reproduce**
1. Create new console app
2. Add TaskScheduler Nuget package to the project
3. Use example code from https://github.com/dahall/TaskScheduler/wiki/Examples#using-the-editor

**Expected behavior**
Dialog class types should be recognized under the TaskScheduler namespace

**Screenshots**
![image](https://github.com/user-attachments/assets/35f7a654-84a6-47e4-aaf4-ab93ec611ba4)
![image](https://github.com/user-attachments/assets/99cbf77d-a913-479e-9692-a0f66ba58799)
![image](https://github.com/user-attachments/assets/7fe7b7a5-09a4-4d17-b237-1ad9f9d1fcf4)

**Environment (please complete the following information):**
 - Host Windows version (the one running the code): Windows 10
 - Library version: 2.11.0
 - Tried with .NET 8 and .NET Framework 4.8.1

**Additional context**
- Documentation mentions assembly version 2.11.1, but latest Nuget version is 2.11.0

**Comment by dahall** [comment]
Have you included both the `TaskScheduler` AND the `TaskSchedulerEditor` NuGet packages? 2.11.0 is the latest published version. 2.11.1 is under development.

**Comment by nahvan9** [comment]
That fixed it! I guess it wasn't intuitive that I needed to include `TaskSchedulerEditor` from the documentation.
Edit: I re-read the readme and it's all there; I probably was only looking at the API documentation.
